### ISSUE TITLE
Bug | Binge Eater

### ISSUE THREAD

**Issue by Romz24** [wofsauge/External-Item-Descriptions#105]
If I am shown 2 items to choose from, I get an error instead of a description.

https://www.youtube.com/watch?v=oGK9_yQ3DYU

To reproduce the bug, give yourself a [Binge Eater](https://bindingofisaacrebirth.fandom.com/wiki/Binge_Eater) (_spawn 5.100.664_), find a store or kill the boss and you will get the same result as mine.

**Comment by wofsauge** [comment]
This bug is fixed now. thanks for the report
