### ISSUE TITLE
Show item descriptions after a pickup (Alt Path/Curse of the Blind)

### ISSUE THREAD

**Issue by ASittingLapp** [wofsauge/External-Item-Descriptions#107]
# Issue 
In both cases picking up an active item while already holding one will still not show a description for the item on that pedestal, despite the player being able to see what it is. This is similar to #83, but includes alt path items. 

I've never tried modding Isaac before, so take my proposed solutions with a huge grain of salt. All I've done is looked at your existing work, and the modding API, and these both sound like they _could_ work, but I obviously don't know what I'm talking about. If I get free time this weekend I might try setting up a Lua environment and looking into this too. 

# Proposed Solution 1:
For Alt Path items I'm wondering if it would be possible to just remove the `EID_IsAltChoise` flag from items on contact/when picked up. 

If that does work, then Curse of the Blind could potentially be handled in a similar way. Similar to `EID:onCollectibleInit` (but outside the REPENTANCE block) an `EID_BlockedByBlind` flag could be added to all item pedestals. On interacting this flag is removed, and to handle Dagaz/Black Candle the description would be blocked `if pickup:GetData()["EID_BlockedByBlind"] and EID:hasCurseBlind()`.

# Proposed Solution 2:
There's a GetSprite method on entities, and if the sprite returned for hidden items is the "?" sprite, this could potentially be used to hide descriptions.

This would be a bigger change, but (if it works) could be very consistent. It would also require extra logic for `EID.Config["DisableOnCurse"])` and `EID.Config["DisableOnAltPath"])` being false.

**Comment by wofsauge** [comment]
This issue should be fixed now. if it still appears, just reopen the issue ;)
