### ISSUE TITLE
Add indicator for items that need to be picked up for achievement

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#109]
Nice to have and requested.

Currently not implementable because its not possible to access savegame data.

**Comment by Ma-rcx** [comment]
Maybe this would be of some use. This site can read "touched" items from the save file. https://zamiell.github.io/isaac-save-viewer/

Source is at: https://github.com/Zamiell/isaac-save-viewer/

It's in typescript, but someone could convert it to lua and implement into EID.

**Comment by wofsauge** [comment]
> Maybe this would be of some use. This site can read "touched" items from the save file. https://zamiell.github.io/isaac-save-viewer/
> 
> Source is at: https://github.com/Zamiell/isaac-save-viewer/
> 
> It's in typescript, but someone could convert it to lua and implement into EID.

This is an external tool which translates the savegame file into human readable data. Since we don't have access to the filesystem via the normal modding api and without luadebug, we can't read that file and therefore cannot access the informations.
Only method I see right now would be a script that creates a list of touched items as a lua file. Then, we can access the infos and work with them. Aka. Marking something as not picked up yet, or updating the pickup state.

**Comment by wofsauge** [comment]
With repentogon, this feature works now without an external tool
