### ISSUE TITLE
Treasure room blind item description may appear in alt floors

### ISSUE THREAD

**Issue by nunuchu42** [wofsauge/External-Item-Descriptions#110]
![image](https://user-images.githubusercontent.com/5581024/120084833-4de6f900-c088-11eb-92f9-5305040a3089.png)
First time this has happened to me. Milk had a blind item description when I moved near. Quitting and loading the game fixes this; I picked up blind the item and can confirm it was Fruit Cake. I had "DisableOnAltPath" as true in the config file.

Apologies if this has been brought up already :)

**Comment by wofsauge** [comment]
thanks for the report, but this bug is known and not fixable with the current api version. sorry

**Comment by wofsauge** [comment]
This issue should be fixed now. thanks for the Report
