### ISSUE TITLE
TMtrainer/corrupted item info?

### ISSUE THREAD

**Issue by DoctorGoat** [wofsauge/External-Item-Descriptions#113]
I apologize in advance if this isn't possible, I have no idea how these items are coded or described or if it's accessible to EID.

It'd be very interesting to have the items generated in challenge 45, with TMtrainer, or with one of Tainted Eden's unlocks describable in some way with EID.

**Comment by wofsauge** [comment]
Thats impossible, since every item is generated on the fly with random, inaccessable effect combinations. There is no way to read what they do.
