### ISSUE TITLE
Turkish translation inquiry

### ISSUE THREAD

**Issue by cagdassalur** [wofsauge/External-Item-Descriptions#119]
I noticed that turkish translation is non-existent for 99% of the items in the game when setting the mod up for a friend. Is it still in progress? If it's abandoned i can take over and start working on a PR.

**Comment by wofsauge** [comment]
Hi. The Turkish translation is sadly pretty much abandoned.
I would be really thankful if you could start working on it :)

**Comment by cagdassalur** [comment]
Will do! Thanks for the quick reply!
