### ISSUE TITLE
Description for Sharp Key in Repentance

### ISSUE THREAD

**Issue by Agom-the** [wofsauge/External-Item-Descriptions#124]
There is missing information: 
"Killing an enemy with a thrown key has a chance of dropping the contents of a Chest; this includes various pickups, consumables, and trinkets."
"these contents can be modified by items that affect chests, such as Mom's Key, The Left Hand, and Gilded Key."

https://bindingofisaacrebirth.fandom.com/wiki/Sharp_Key

**Comment by wofsauge** [comment]
This description is fixed now. Thanks for the report :)
