### ISSUE TITLE
"Uninstalling!!~external-item-descriptions" on game start

### ISSUE THREAD

**Issue by breadtard** [wofsauge/External-Item-Descriptions#127]
hi yes hello so basically 
when i start the game with the mod loaded, this screen shows up
![image](https://user-images.githubusercontent.com/77245194/123134585-3ca7c700-d451-11eb-89b6-d0e5774fb3ca.png)
and then the mod gets deleted from the folder
what the hell do i do

**info:**
OS: Arch Linux x86_64 (but running through lutris so the game thinks that i use windows)
Isaac DLC: Repentance (pirated but shut)
Lutris runner version: lutris 6.0
Yes i beat mom and mom's heart on the save file

**Comment by wofsauge** [comment]
Hi. In order to prevent this, you need to:
1. Delete the "metadata.xml" file from the mod
2. If needed, rename the mod folder so that it does not contain any number

**Comment by breadtard** [comment]
worked, thanks
