### ISSUE TITLE
Download for crack

### ISSUE THREAD

**Issue by YukiOnGithub** [wofsauge/External-Item-Descriptions#128]
So i currently have a cracked version of repentance and i was asking about a download separate from steam to be able to have the mod. Have a good day.

**Comment by wofsauge** [comment]
Just press the download button of this repo?

All you need to do afterwards is unpack the .zip file , put it in the mods folder like any other mod and delete the Metadata.xml file.

**Comment by YukiOnGithub** [comment]
Oh well i guess i'm blind thanks for the help 👍
