### ISSUE TITLE
Blind treasure room choices from Broken Glasses will display description

### ISSUE THREAD

**Issue by Gemboat** [wofsauge/External-Item-Descriptions#144]
The Broken Glasses trinket gives a chance for a main-path treasure room to have an blind extra choice of item in it. The EID description for this item will always show fully, even with the relevant settings that should prohibit it.
It looks like this is due to overzealous performance-boosting, only checking for alt-path items on the actual alt-path. Removing the `game:GetLevel():GetStageType() < 4` check from `EID:IsAltChoice()` fixes this without noticeably harming performance.

**Comment by wofsauge** [comment]
Fixed this issue now. Thanks for the report :)
