### ISSUE TITLE
Only show descriptions for seen items

### ISSUE THREAD

**Issue by Bill-Pill** [wofsauge/External-Item-Descriptions#145]
Would be nice if there was an option to only show descriptions for items seen/equipped previously. This can aid newer players who are a bit overwhelmed by the hundreds of items in the game but also want to retain a sense of experimentation and discovery.

**Comment by wofsauge** [comment]
This feature gets requests often, but its impossible to implement with the current api because we can't access the "picked up" state of the items.
Sorry
