### ISSUE TITLE
No Machine in shops

### ISSUE THREAD

**Issue by senwho** [wofsauge/External-Item-Descriptions#148]
Hey i´ve occured the problem, that my shops wont have the bank, so i cant save or take money. Playing on Cracked (repentence), win10 .

**Comment by wofsauge** [comment]
This mod does no alterations to spawn behaviors of anything. Its a pure informational mod.

The only situation where the donation machines don't spawn is, when you are playing a challenge.

**Comment by senwho** [comment]
I´ve tried normal/hard with new profile on isaac, no dono machine with mod but works just fine with it being disabled

**Comment by wofsauge** [comment]
Did you kill mom at least once on your save file without mods in order to actually onlock mod support and them being usable without disabling achievements?

**Comment by senwho** [comment]
I did not, i beat her after installing the mod tho. So should i disable -> kill mom -> try again?

**Comment by wofsauge** [comment]
Yes

**Comment by senwho** [comment]
works perfect thanks
