### ISSUE TITLE
Problem with main.lua line 97 

### ISSUE THREAD

**Issue by Tomipedia** [wofsauge/External-Item-Descriptions#151]
I have this error pop up at the start of the game, making the addon unusable. I use x64 Windows 10 Pro. I don't have any other mods installed.
![main](https://user-images.githubusercontent.com/90012723/131935375-9c38073e-5318-4910-a72a-acd73beaa2db.png)

**Comment by wofsauge** [comment]
remove the --luadebug   attribute you have set in steam as the launching flag.

**Comment by Tomipedia** [comment]
it worked, thanks a lot!
