### ISSUE TITLE
Bag of Crafting for Mods

### ISSUE THREAD

**Issue by DolosKurosu** [wofsauge/External-Item-Descriptions#155]
Is it possible to make it so that end-users can provide updated/modified itempools for the bag of crafting algorithm?

As far as the main algorithm by BladeCoding goes, I was able to generate accurate recipe lists for modded pools. The only question is if there's a way for users to manually add their itempools to EID for the algorithm.

**Comment by wofsauge** [comment]
right now, this can only be achieved by altering the "itempools" table inside the eid_bagOfCrafting.lua file. 

If needed, i could provide a small python script in the future that generates the content of that table based on the installed mods.

**Comment by DolosKurosu** [comment]
Very interesting idea. Sounds like a lot of work, but the idea is cool. I'll see if I can write a js program to do that. I already have everything I need in the bag-of-crafting program I made.

**Comment by DolosKurosu** [comment]
I did it. I made a program that outputs txt files with tables exactly like yours in EID.

**Comment by wofsauge** [comment]
Nice thank you :)

**Comment by DolosKurosu** [comment]
I tried inputting my tables, and removed the mod error message on my copy of EID. The items on the display are different from vanilla as anticipated, but they show the wrong items. For example, 8 coins in Item Pool Rework Mod gets you Telepathy for dummies, but instead shows Box.

**Comment by DolosKurosu** [comment]
> Nice thank you :)

You are most welcome

**Comment by wofsauge** [comment]
When I have some time on hand I could make it work, so that you only have to paste the file into the folder of the mod in order to overwrite the vanilla informations. For that though, it needs to be a .lua file with a different name. For example like "moddedItemPools.lua" or something

**Comment by DolosKurosu** [comment]
that's easy. I just made the output files txts cuz it's standard, but I can make it output lua docs instead.

**Comment by wofsauge** [comment]
> I tried inputting my tables, and removed the mod error message on my copy of EID. The items on the display are different from vanilla as anticipated, but they show the wrong items. For example, 8 coins in Item Pool Rework Mod gets you Telepathy for dummies, but instead shows Box.

It could be the way you parse the itempools but I dont know for sure.
It can maybe also just be caused by simply not having the item u locked already, which you want to craft. In that case, it will calculate some different results.

 Also, when parsing the updated itempools.xml file, the location of the file is very important. If its in the resources folder of a mod, then it overwrites the existing itempool configuration of the game. If its located in the content folder, it works additive, meaning it adds the defined items to the itempools. In both cases, the itempools.xml file can have ids as well as itemnames in their item definitions. Those need to be matched to the correct items as well.

**Comment by DolosKurosu** [comment]
> > I tried inputting my tables, and removed the mod error message on my copy of EID. The items on the display are different from vanilla as anticipated, but they show the wrong items. For example, 8 coins in Item Pool Rework Mod gets you Telepathy for dummies, but instead shows Box.
> 
> It could be the way you parse the itempools but I dont know for sure.
> It can maybe also just be caused by simply not having the item u locked already, which you want to craft. In that case, it will calculate some different results.
> 
> Also, when parsing the updated itempools.xml file, the location of the file is very important. If its in the resources folder of a mod, then it overwrites the existing itempool configuration of the game. If its located in the content folder, it works additive, meaning it adds the defined items to the itempools. In both cases, the itempools.xml file can have ids as well as itemnames in their item definitions. Those need to be matched to the correct items as well.

I was using a speedrun dead god file to playtest, so it isn't an unlock issue. so probably a parse issue.

**Comment by DolosKurosu** [comment]
Okay. I discovered that whichever icon replaces an item replaces all recipes for that item. Box appears for every Telepathy for dummies recipe. However, Deck of Cards is completely untouched. I'm starting to think this has more to do with Icon rendering than the item calcs.

**Comment by DolosKurosu** [comment]
I tried printing out the `multi` float you use to calculate the results. It prints out `2.3283061589829E-10` instead of `2.3283061589829401E-10` I think lua is cutting off your `multi` float and resulting in minor ID calc errors. I think the Bag of Crafting  program will either need an additional error term at the end to round off the differences, or more/different hardcoded recipes to correct the code. I'll try to figure it out.

**Comment by DolosKurosu** [comment]
> I tried printing out the `multi` float you use to calculate the results. It prints out `2.3283061589829E-10` instead of `2.3283061589829401E-10` I think lua is cutting off your `multi` float and resulting in minor ID calc errors. I think the Bag of Crafting program will either need an additional error term at the end to round off the differences, or more/different hardcoded recipes to correct the code. I'll try to figure it out.

This has nothing to do with it.

**Comment by wofsauge** [comment]
Hmm weird. My code should definetly return the same values as the other implementations of the tool, since its exactly the same code. 
Hopefully you can find the issue.

**Comment by DolosKurosu** [comment]
yeah I plan to dissect the outputs used in your function regarding the calculations and rendering.

My first guess is your `nextFloat()` function's `multi` variable because it's too small to record all the digits in lua.

My second guess is that it has nothing to do with the calcs and is instead a render issue.

I have other things to try, and I'll share my findings when I am done combing through everything.

**Comment by DolosKurosu** [comment]
nvm. it was me. I made a mistake that removed some quality 0s from `EID.itemWeightsLookup`. I fixed the program, and fixed the table in my EID. I'll let you know the results.

**Comment by DolosKurosu** [comment]
Btw, one of the items my program removed was Telepathy for Dummies. Ooooof.

**Comment by DolosKurosu** [comment]
IT WORKS!!!

**Comment by wofsauge** [comment]
> IT WORKS!!!

Nice!

**Comment by Buurazu** [comment]
I was thinking about this more and might try to implement a backup attempt for when modded items are detected, now that I know more about how the bag works.

All that we need to know for the Bag of Crafting is the contents of the pools it pulls from (Treasure, Boss, Shop, Angel, Devil, etc): The items in the pool, those item's weight in the pool, and those item's quality.

Item quality is easily checkable; the contents of item pools can be determined using the RoomBlacklist method as long as the items are unlocked and still in the pool; and as far as I can tell there's no good way to get the weight, so we'd have to assume 1.0. (I might test collecting results from spamming GetCollectible and see if rounding to the nearest tenth is realistic)

So, it should be able to at least work for mods that have their items always unlocked with weight 1.0.

It's a bit sad that mods have nearly no access to itempools.xml's content...

**Comment by Buurazu** [comment]
I tested the feasibility of determining item weight and I don't think it's feasible at all; it seems that your starting seed heavily affects the chances of equal-weight items (tested with Quarry Collection, all items are weight 1 in treasure pool): https://i.gyazo.com/4658bb12752ff5582dbfd7273b47d158.png
But assuming weight 1.0 will help it be usable for many mods at least

**Comment by wofsauge** [comment]
> I tested the feasibility of determining item weight and I don't think it's feasible at all; it seems that your starting seed heavily affects the chances of equal-weight items (tested with Quarry Collection, all items are weight 1 in treasure pool): https://i.gyazo.com/4658bb12752ff5582dbfd7273b47d158.png But assuming weight 1.0 will help it be usable for many mods at least

Yeah. Without being able to read the exact itempool weights from the itempools.xml file, I dont think it's possible

**Comment by wofsauge** [comment]
The Feature is implemented in a state which works ok for most item mods except Ipecac Community mod.

But in this stage, i would go as far as to say that this issue can be closed and any further improvement either requires a Modding API update, or just bug fixing
