### ISSUE TITLE
Number Magnet lack of information

### ISSUE THREAD

**Issue by Dragom-the** [wofsauge/External-Item-Descriptions#156]
https://bindingofisaacrebirth.fandom.com/wiki/Number_Magnet

Its missing this:
Prevents Krampus from appearing in the Devil Deal.
If held before visiting the Devil Deal, the room's layout will be replaced with one of 11 special Devil Room layouts (6 in Greed Mode). These rooms contain 0-3 Devil Room items (most commonly 2-3), 1-3 Black Hearts, and several enemies from Sheol

**Comment by wofsauge** [comment]
Added these informations now. thanks for the report
