### ISSUE TITLE
Spindown Dice is skipped when it shouldn't

### ISSUE THREAD

**Issue by OciXCrom** [wofsauge/External-Item-Descriptions#163]
As you can see on the image below, Spindown Dice (723) should appear as a result after Hypercoagulation (724). The dice can reroll into itself.

![The Binding of Isaac  Rebirth Screenshot 2021 10 15 - 15 18 58 96](https://user-images.githubusercontent.com/14963855/137496056-08cdf4fc-2837-446b-b252-235f82e7bc33.png)

**Comment by wofsauge** [comment]
seems like you fixed this issue in your pull request already. Thank you :)

**Comment by wofsauge** [comment]
> @wofsauge are you sure? This was not one of the ids that was wrong. I did try fixing it but I couldn't locate the problem. I updated the mod and the issue is still there.

Ive fixed the issue now myself. it was a problem with the Bulletpoint icon detection, not the spindown dice description itself.
