### ISSUE TITLE
Bag of Crafting

### ISSUE THREAD

**Issue by Ma-rcx** [wofsauge/External-Item-Descriptions#182]
v1.7.5 completely broke Bag of Crafting, it needs to be updated.

![isaac-ng_AD93C9N0Ce](https://user-images.githubusercontent.com/55658162/141323849-f9e65649-fc06-485c-9986-5ce92c4a9881.png)

**Comment by wofsauge** [comment]
Removed the feature for now in commit 60e7f7bec62c1e0b89b292fc7685eeb3386d75b9

Until we dont have a reverse engineered version of the new algorithm or know how it exactly works, we cannot add the feature back.

**Comment by bubbyboytoo** [comment]
On this topic, would it be possible to add support for showing the info of the item you've currently got in the bag's crafting result, before you actually craft it?

**Comment by wofsauge** [comment]
That feature was already a thing before the patch. Therefore  it will be possible again

> On this topic, would it be possible to add support for showing the info of the item you've currently got in the bag's crafting result, before you actually craft it?

**Comment by Ma-rcx** [comment]
Maybe add a hotkey to switch between the crafted item's description and the bag of crafting recipe infos?

**Comment by Ma-rcx** [comment]
This was fixed. :)
