### ISSUE TITLE
"Hide" key broken

### ISSUE THREAD

**Issue by MrLavender** [wofsauge/External-Item-Descriptions#183]
When using a controller F2 no longer hides. Instead it is mapped to controller `ButtonAction.ACTION_SHOOTUP` even though it is set to the default `Keyboard.KEY_F2` in my config.

>lua print(EID.Config["HideKey"])
291
>lua print(EID.player.ControllerIndex)
1

[This change looks wrong](https://github.com/wofsauge/External-Item-Descriptions/commit/09dcd449281fb82670424d67b99684131d6f615b#diff-cee6f7ace765d4b3e8274806fb658676b5f550810b495d8987ea30ab1121ea73). I don't know why `Input.IsButtonTriggered(291, 1)` is returning `true` when I use `ButtonAction.ACTION_SHOOTUP` but the controller index surely needs to be 0 for keyboard input.

**Comment by wofsauge** [comment]
fixed now

**Comment by MrLavender** [comment]
Thank you!

And thanks for the great mod, a much nicer way to play BoI.
