### ISSUE TITLE
Bag of Crafting Algorithm

### ISSUE THREAD

**Issue by frto027** [wofsauge/External-Item-Descriptions#189]
It is disassembled from the game. 
It is not very precise, but I have not seen this situation. It may be because javascript uses double, while the game uses float.
algorithm: https://github.com/frto027/IsaacDisassemblyRate/blob/master/BagOfCrafting/BagOfCrafting_rep_new.js
preview in web browser: https://frto027.github.io/IsaacDisassemblyRate/calculator/bag/index.html

**Comment by wofsauge** [comment]
Awesome 👌 thanks :) I will try to implement that algorithm after my holidays (2 weeks)

**Comment by Buurazu** [comment]
I will definitely look into this, thank you so much! I've handled a bit of disassembly before but had no clue how to locate the code

**Comment by Buurazu** [comment]
Oh, is there anything you can say about how you got the code from the EXE? In case of future updates

**Comment by frto027** [comment]
> Oh, is there anything you can say about how you got the code from the EXE? In case of future updates

I use Cheat Engine to search for the address of crafted item id, and then use a memory breakpoint to find the code that wrote it, and the function is nearby.

**Comment by Buurazu** [comment]
Interesting, I tried to attach the cheat engine debugger to when the RNG seed is accessed, and grabbed 8 items, and it crashed. Maybe the write debugger is better

**Comment by frto027** [comment]
Maybe the stability depends on the hardware. Just use CE to find the address, and then try other debuggers like windbg or ida. I didn't remember exactly, but the RNG object maybe on the stack instead of heap, it can't be searched.

**Comment by wofsauge** [comment]
the new bag of crafting algorithm is now implemented in the mod. therefore this issue can be closed i think
