### ISSUE TITLE
Mod does not work since patch 1.7.5

### ISSUE THREAD

**Issue by Synochy** [wofsauge/External-Item-Descriptions#190]
Hello,
Since the patch 1.7.5 the mod is not working anymore. 
The error in the log file is: 
Lua Debug: EID - ERROR: Could not load font from 'E:\Program Files (x86)/Steam/steamapps/common/The Binding of Isaac Rebirth/lua/resources/font/default.fnt'
Indeed the directory LUA does not exist. 
I tried to uninstall/install the mod but it still doesn't work. 
Could you help me with this problem ?
Regards,

**Comment by wofsauge** [comment]
The mod does work for me and all people I know. So it must be definetly a problem caused by your installation.
First, make sure to have the --luadebug flag disabled. If you don't know what that is  then you definetly have it disabled.
Second, use the steam feature to verify the integrity of the game files. This can fix faulty installations of the game.
Third, if you manually installed the mod, make sure the mod folder is called "external item descriptions_836319872"

**Comment by Synochy** [comment]
I uninstall everything (mod + game).
Then I install the game and the mod.

I have a new error:
[INFO] - Running Lua Script: E:\Program Files (x86)\Steam\steamapps\common\The Binding of Isaac Rebirth/mods/external item descriptions_836319872/main.lua
[INFO] - Lua Debug: EID - ERROR: Could not load font from 'C:\Users/_user_/Documents/My Games/Binding of Isaac Afterbirth+ Mods/external item descriptions_836319872/resources/font/default.fnt'
[INFO] - Lua Debug: EID - ERROR: Could not load font from 'C:\Users/_user_/Documents/My Games/Binding of Isaac Afterbirth+ Mods/external item descriptions_836319872/resources/font/default.fnt'

I don't know why it goes in this file because the only directories that exists are:
C:\Users\_user_\Documents\My Games\Binding of Isaac Repentance
or
E:\Program Files (x86)\Steam\steamapps\common\The Binding of Isaac Rebirth\mods\external item descriptions_836319872\resources\font

**Comment by wofsauge** [comment]
Hmm then maybe you need to copy the mod in the "my games" folder, too. Normally that folder is used to store mods when the ab+ dlc is installed. All mods get copied there first. With repentance, that folder got changed to the mods folder in the game files. The game will then copy all mods from the ab+ mods folder into the new one.
Maybe there is some oversight from my side that it needs that ab+ folder. So for now, just make sure that this folder also exist and contains the file.

I will try to find a fix for that issue after my holiday in two weeks

**Comment by Synochy** [comment]
I created the directory and now it works thanks for the fix !

**Comment by wofsauge** [comment]
I moved this problem to issue #204 now. That way we have a clearer problem description :)
