### ISSUE TITLE
Synergies

### ISSUE THREAD

**Issue by Ma-rcx** [wofsauge/External-Item-Descriptions#195]
Below the item description, display if the item has any meaningful synergies with any of the currently held items. This could however be a long list if the player has many items, so something at the end saying "!!! This item has synergies with some of your held items - press [some key] to open/scroll through them"

This could result in having to implement pages to scroll through and similar stuff.

Just an idea I've had that would be very cool to see, but I know it could take an incredibly big amount of work to properly implement. At the very least, we can do the most important synergies players should know first and then work our way down the items. All of this could be done on a new branch, so if this gets scrapped and while the work is going on, there's no harm done to the actual mod.

**Comment by wofsauge** [comment]
Thats an extremely ambitious plan. Even if one item only synergies with two other items, that would be 1600 new descriptions that all need to be written and translated in all currently available languages.
An easier way would be, to just list all items it synergies with, but don't show a written info what exactly it does. This way, we can use the item icons to show synergies and don't need text.
That makes it also easily automated le by using a webscraper on the wiki to get all synergies.
Additionally, we could somehow keep track of negative synergies.

**Comment by Buurazu** [comment]
Appending lines to descriptions for synergies based on what the players have/are is now supported in a relatively easy-to-add way with eid_conditionals.lua.
If more complicated code is needed to determine what to print (Consolation Prize, Void), or per-player info is desired (Birthright, pill effects), it's handled by eid_modifiers.lua.
