### ISSUE TITLE
Indicator is in the incorrect location when passing through the mirror in Downpour/Dross

### ISSUE THREAD

**Issue by darkevilmac** [wofsauge/External-Item-Descriptions#197]
When obtaining the first knife piece in the alt path all of the indicators are in the incorrect location. I'm not sure if there's an API call that can be made to check if the screen has been horizontally flipped but if that's the case then it should just be a matter of making the indicator relative to the other side of the screen.

You can see an example here, the red indicator above the trinket should be on the opposite side of the screen.
![image](https://user-images.githubusercontent.com/1813540/141705022-5d75c44e-78d7-4dfd-b1f9-1bb471f52f66.png)

**Comment by Buurazu** [comment]
this bug is cute but definitely worth fixing now that there's a "is mirror world" lua function available to mods

**Comment by wofsauge** [comment]
bug is fixed with the issue mentioned aboth
