### ISSUE TITLE
Setting to display total quality of pickups as an alternative to the recipe display

### ISSUE THREAD

**Issue by namishere** [wofsauge/External-Item-Descriptions#199]
I never enjoyed playing T. Cain pre-patch because it felt like a chore to find the mandatory pickups required to craft the right items to break the game.
Now that recipes aren't always the same, and there's greater incentive to strategize what pickups you swipe, it would be nice to have an alternative to the recipe display that instead keeps track of what quality each pickup is, your cumulative quality, and what tier that quality falls under. This way, you'd still be encouraged to play T. Cain as intended while also eliminating some mental math keeping track of exactly how good your pickups are.

**Comment by namishere** [comment]
The "simplified mode" as described in #201 would resolve this issue if implemented.

**Comment by Buurazu** [comment]
yeah, although I am loving doing a degen mama mega + R key extravaganza, I can respect people wanting a more intended "influence the luck in your favor" experience
if you could give an example layout for how to display the info, that could help, not sure what would be best yet

**Comment by wofsauge** [comment]
cool new mode was implemented in the issue mentioned aboth. therefore, this issue can be closed i think.
