### ISSUE TITLE
Mod cant find font files, if the mod doesnt exist in the ab+ folder

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#204]
IMPORTANT ISSUE TO FIX!!!

If the user only has the mod installed in the repentance mods folder, but not in the ab+ mods folder, the mod can't find the font file. This makes the mod unusable.

Potential cause of this issue:
Line 127 in main.lua file.

Right now, it assumes the game is looking in the scripts folder of the gamefiles for the font. Thats why we use ../ to go one folder up, then go into the mods folder and then the "external item descriptions" folder to find the real font file.

Problem: maybe the game no longer starts to search in the scripts folder, but another folder entirely.

**Comment by wofsauge** [comment]
@Buurazu are you interested in maybe looking into this? It might just be an easy fix.

Possible things to try out could be:
"../mods/"..modfolder.."/resources/font/eid_"..fontFile..".fnt")

**Comment by Buurazu** [comment]
Hmm, I can't reproduce it by getting rid of the AB+ folder.
I tested printing the mod path and seeing where the font success is for me, the modpath is as it should be and the first font check is a success (so it never hits line 127).
I notice that EID.modPath gets set to the old AB+ location inside the isluadebug block; if only that one person has reported this bug, I'd have to assume that he kept luadebug on (that first error that tried to look for a nonexistent "lua" folder started with "Lua Debug:") and therefore triggered that block.

**Comment by frto027** [comment]
This bug was triggered when I enabled luadebug. Maybe try the following code.
```
local function GetCurrentModPath()
    if debug then
        return string.sub(debug.getinfo(GetCurrentModPath).source,2) .. "/../"
    end
    --use some very hacky trickery to get the path to this mod
    local _, err = pcall(require, "")
    local _, basePathStart = string.find(err, "no file '", 1)
    local _, modPathStart = string.find(err, "no file '", basePathStart)
    local modPathEnd, _ = string.find(err, ".lua'", modPathStart)
    local modPath = string.sub(err, modPathStart+1, modPathEnd-1)
    modPath = string.gsub(modPath, "\\", "/")
    
    return modPath
end
```

**Comment by wofsauge** [comment]
after some testing, this issue should be fixed now i think. please reopen the issue with more detailed bug infos if it appears again
