### ISSUE TITLE
The value of parameter remains true after changing any config parameter containing true/false

### ISSUE THREAD

**Issue by kochetov2000** [wofsauge/External-Item-Descriptions#218]
I do not use the Mod Config Menu and I edit the mod's configuration manually, so config cannot be loaded from any external source. But If I change the value of any parameter in config from false to true and then vice versa, for some unknown reason, when i'm trying to get value of parameter in the console it returns only true

**Comment by wofsauge** [comment]
Make sure you edit the config file in the correct folder.
For repentance, that would be the game installation path + mods/external item descriptions.
For ab+, it would be in the user folder as described in the mod description

**Comment by kochetov2000** [comment]
Of course i edit the config in the correct folder. I use repentance

**Comment by wofsauge** [comment]
How are you trying to access the config via the console? Normally, if you don't change the config via mcm, you don't need to do that via the console.
And did you try to delete the data files of the mod, found in the data folder next to the mods foder?

**Comment by kochetov2000** [comment]
Ok. Deleted .dat files and put a small crutch in code (main.lua, string 820, changed isDefaultConfig to false) and it works)
