### ISSUE TITLE
Config version increase resets all settings

### ISSUE THREAD

**Issue by Buurazu** [wofsauge/External-Item-Descriptions#254]
Upping the EID.Config.Version for local mode made all settings revert to default, which doesn't seem right
But, I have no clue how mod updates work with people who have modified the eid_config.lua file directly (doesn't it always replace their config with a fully default one?), so I don't want to touch this kind of thing personally and break something I didn't understand
Looking at the code in line 860 of main.lua, it already handles possible type mismatches, so I'm not sure what the harm would be in keeping valid settings across config versions

**Comment by wofsauge** [comment]
The reset feature is intentionally programmed that way. Therefore its intended to reset the config files. Its not needed to be reset tho, so I will revert the change now. This should prevent a global reset

**Comment by wofsauge** [comment]
config version is now reverted. it should not reset the config for all people anymore
