### ISSUE TITLE
Add glow effect to in-bag components in 8 Icons display

### ISSUE THREAD

**Issue by Buurazu** [wofsauge/External-Item-Descriptions#256]
The green text for completed components was a really great idea! Thank you!
But now 8 Icons is lagging behind...

I'm not sure if there's a better way to do this than just a 2nd copy of the crafting icons PNG that's been modified externally to be green. Considering how easily Isaac's skin tone is able to be shifted, I'd guess there are definitely functions to apply that kind of color change to drawn images, but I'm not familiar with that kind of Isaac modding yet so I figured I'd suggest it here than try to implement it

Also, just a color applied to them might look ugly or not different enough for some components; a pulsating glow (like Cards have when you own Tarot Cloth) might be better

**Comment by wofsauge** [comment]
Implemented with commit ce320f5062ade14b867ac25d6c5f61bc1aa811ca
