### ISSUE TITLE
Line breaks cause {{ColorReset}} to fail

### ISSUE THREAD

**Issue by Buurazu** [wofsauge/External-Item-Descriptions#267]
![](https://i.imgur.com/BYh4KDz.png)
({{CR}} after "heart")
I can see in EID:printBulletPoints that the color is carried over line by line, and EID.LastRenderCallColor gets set at the beginning of each line to whatever the starting color of that line is
Not sure what you'd like to do to fix it, personally I'd say as a "reset" that ColorReset should always just return the default text color, but then it's kind of redundant to {{ColorText}}
For now I'll just use {{ColorText}} instead of {{CR}}

**Comment by wofsauge** [comment]
This issue is fixed now with commit d9ade75c00dbe8ccf37ae40078697acb8466ff0b
