### ISSUE TITLE
Bag of Crafting bug in Greed

### ISSUE THREAD

**Issue by ZeroplaysMC** [wofsauge/External-Item-Descriptions#283]
For some reason, Tainted Cain's seeded bag recipes don't show up in greed mode after you use it once.... then doesn't work until i restart the game. For example;

I get the resources, then search and craft Steam Sale.
Then... it doesn't work until i completely close the game and open it again. Am I missing something or doing something wrong?
Thanks either way.

**Comment by Buurazu** [comment]
If you have 8+ pickups on the floor and no display comes up until closing and reloading the file, I would like to know if there's any error output in the in-game debug console
and I would need your mod list because I don't think it's reproducible with EID alone

**Comment by Ma-rcx** [comment]
@ZeroplaysMC you still having that issue?

**Comment by wofsauge** [comment]
ive tested around a bit and i cant reproduce this problem. Maybe it was already fixed in a previous patch.

If this issue still occurs, please reopen the issue and maybe post the error message you get in the Debug console or your log.txt file.
