### ISSUE TITLE
Add missing icons to markup

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#287]
Would be nice to have icons for stats in markup, and probably pretty easy to do since they already are in the game. It will also be useful to clear up ambiguity in certain languages. If they're already in there, they are not in the markup page in documentation

The icon for Broken Hearts and active Holy Mantle would be useful as well since they are not supported yet

**Comment by Ma-rcx** [comment]
I like the idea, but make it a toggle. I'm not sure that everyone wants to use them and they may add more clutter. 

Also, this is going to be a pain to implement (unless we make adding the icons automatic), but I wouldn't mind the work.

**Comment by Buurazu** [comment]
I think that is an interesting idea. Although currently the bullet point is replaced with an Up Arrow or Down Arrow for all basic stat up/downs which is probably better info than a stat icon. Would it go "↑ +0.7 {{Tears}}Tears up"? That could be too much.
Also, the stat icons in the extra hud might be a bit too big to be inline icons like that. I tried adding the true co-op character heads as inline transformation icons before (for birthright mostly) and it did not work out at all.
Somewhat related, I noticed while using The Quarry Collection for mod compat testing that they used heart icons for heart lines which is kinda cool and probably better than a bullet point or up arrow:
![image](https://user-images.githubusercontent.com/2997591/148483488-b5b2e4fe-c566-46f6-bc2c-a060ac8ccf39.png)

**Comment by biobak64** [comment]
I'm currently reworking the french translation of the mod which is outdated and a bit messy and this is what I'm doing with hearts and pickups as well. 

I'm not asking to actually put them in the descriptions, just to have the option to use them if necessary. These icons would 100% be optional and up to the person writing the descriptions, but it would be nice to have them, one idea that comes to mind is "{{Luck}} Is affected by the luck stat" for tear modifiers. In French, "a chance to" and "luck" are the same word, so it would be good to have an icon to differentiate them when the context makes it confusing or when clearer wording is not possible.

**Comment by Buurazu** [comment]
An option/toggle is tricky because we definitely don't want two copies of the main descriptions, but descriptions are just a simple string, so the only thing to do is find+replace certain parts of the string. We'll see.

**Comment by biobak64** [comment]
I think the way I wrote my comment was a bit confusing, I'm sorry. I'm just asking if it's possible to have these icons added to the icons bank so modders and translators can use them in their descriptions. This would not be a toggle for players, just more icons 
 for the people who write descriptions to use.

**Comment by Ma-rcx** [comment]
> An option/toggle is tricky because we definitely don't want two copies of the main descriptions, but descriptions are just a simple string, so the only thing to do is find+replace certain parts of the string. We'll see.

My idea was to make a function that uses regex to determine if there's a stat involved (what you mentioned before), so e.g. if there's a "+1 Damage up" it would add the damage icon in front of it before it gets rendered on display. Also add a config/mod menu entry so if it's disabled, the function doesn't do anything.

**Comment by wofsauge** [comment]
![image](https://user-images.githubusercontent.com/245725/148617505-02350a6b-1379-4830-b64d-c9eba2a5f384.png)
Ive added these stat icons now. let me know if you need anything else.

In general, the Regex method would be the best to automatically add the icons. and Toggling can easily be done with that method as well, since it just turns that regex function on or off.

**Comment by biobak64** [comment]
ahhh you're the best. I noticed the icons for Holy Mantle (in the health bar), broken hearts and red item rooms (from Devil's Crown) seem to be missing too, can these be added as well ?

**Comment by wofsauge** [comment]
![image](https://user-images.githubusercontent.com/245725/148624001-0bb764ef-3114-4cda-8fd6-d0d0f8fc4154.png)
Ive added those icons as well now :)

**Comment by wofsauge** [comment]
Closing this issue because icons got added successfully. 

If the toggling of stat icons via regex method should be implemented, an additional issue should be created for it
