### ISSUE TITLE
"Name language" setting returns false results for the achievement warning

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#296]

**Comment by Buurazu** [comment]
The "Next Sacrifice Room payout" printouts on Current + English should be fixed now, I disable the English printout if displayingPermanentText is true

**Comment by wofsauge** [comment]
Ive tested the following features now, and it works properly now:
- Achievement warning text
- Sacrifice room
- Dice room
- Items
- Crane Game
