### ISSUE TITLE
"TextboxWidth" option should be in MCM options

### ISSUE THREAD

**Issue by kohashiwakaba** [wofsauge/External-Item-Descriptions#300]
Korean language pack is recently updated, but there was a slight problem that the boxwidth of EID was too small to display many text for Korean language(or English Detailed).
Many people rely on Mod Config Menu to change EID options and maybe they don't even know about existence of "TextboxWidth" option.

I also suggest adding LineHeight option for EID.

**Comment by wofsauge** [comment]
Added a config option for textbox width and Lineheight now :)
