### ISSUE TITLE
Death Certificate area with Curse of the Blind

### ISSUE THREAD

**Issue by valentinLampriere** [wofsauge/External-Item-Descriptions#319]
With Curse of the blind items are replaced with question marks and EID do not display the description of the item.
Death Certificate area is a special place with all items in the game, all of them are revealed even with Curse of the Blind.

With Curse of the Blind, in the Death Certificate area items are revealed but their descriptions aren't displayed so we do not have their effects

**Comment by Buurazu** [comment]
This should be fixed in the next Workshop release

**Comment by wofsauge** [comment]
This issue was fixed
