### ISSUE TITLE
Bag of Crafting stays hidden while holding a consumable

### ISSUE THREAD

**Issue by Sad-theFaceless** [wofsauge/External-Item-Descriptions#324]
Hello!

The Bag of Crafting won't work anymore if the player is holding a card (and maybe the other consumables too), despite pressing F3 (can't really see that in video unfortunately)

https://user-images.githubusercontent.com/21340420/150039139-1b15c44a-6f6c-435b-ab60-173b4a0bfbe7.mp4

**Comment by Buurazu** [comment]
Picking up the card reduced the loose ingredients on the floor from 8 to 7. Not a bug.
However, it can then turn into a feature request of checking the player's pickups for cards/pills/runes/etc. and including them in the Floor total.

**Comment by Buurazu** [comment]
Bag of Crafting now checks all player's inventories for cards/pills and adds them to the floor count
