### ISSUE TITLE
Start making github releases

### ISSUE THREAD

**Issue by Ma-rcx** [wofsauge/External-Item-Descriptions#327]
Would be nice if people could download release versions directly from here. 

It might be a bit time consuming though, but viable if we could automate it.

**Comment by wofsauge** [comment]
Ive made the first Release version of EID now. Let me know if that is how you expected it to be:

https://github.com/wofsauge/External-Item-Descriptions/releases/tag/V4.14

**Comment by Ma-rcx** [comment]
Yes, that's great. However I still find that automating releases would be way easier. 

Change logs can be auto-generated if we switched to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format ([summary](https://www.conventionalcommits.org/en/v1.0.0/#summary)) and there are bots to create a release once a condition is met. 

Hopefully this can be implemented by switching to the [SemVer](https://semver.org/) versioning specifications and having a bot read new changes to the version string (maybe?) or on creating a new tag and auto-releasing with change logs of all prior commits up until the last version.


I know these are a lot of proposed changes, with some being slightly more major, but automating it would be easier on you.
Let me know what you think @wofsauge 😄

**Comment by wofsauge** [comment]
For now, Conventional Commits is a bit hard to convey to every participant.
SemVer Versioning only makes sence for releases in between workshop commits, because the Workshop version is only a Major and Minor number.

Therefore, we for now only do manual releases that are released the same time as workshop releases
