### ISSUE TITLE
Show the Pandora's box reward

### ISSUE THREAD

**Issue by Sad-theFaceless** [wofsauge/External-Item-Descriptions#365]
I think displaying the current floor's reward while the box is held could be a nice addition (kinda in the same mindset as #350 )

**Comment by Buurazu** [comment]
We should have one issue for compiling a list of active items that have a previewable effect like this.
My current plan is to have a description with a list of your active item's next effect when you hold Map (Tab/Back). there can be two config settings for it, one for showing logical results (tele 2.0, pandora) and one for RNG results (crooked penny, d1)

**Comment by wofsauge** [comment]
This feature is now implemented with the "Item Reminder" feature
