### ISSUE TITLE
Texts will be behind the hearts a little when using Magdalene with over 12 hearts

### ISSUE THREAD

**Issue by Xheepey87** [wofsauge/External-Item-Descriptions#367]
![Snipaste_2022-02-02_09-24-32](https://user-images.githubusercontent.com/40490528/152079038-78e07d85-f192-4b6e-bb5c-5d81fa5edcfa.png)
With Birthright, Magdalene can have hearts over 12, where the item's name could be behind the third-line hearts. Maybe it should have some offset just like tainted Isaac.

**Comment by Buurazu** [comment]
Fixed with a little 5 pixel offset when playing as Magdalene that owns Birthright

**Comment by Ma-rcx** [comment]
Descriptions also overlap with pills/cards/etc. when playing as J&E (or when playing co-op).

**Comment by Buurazu** [comment]
Added a J&E offset, and a rightward offset for Greed Mode (wave counter is too large)

I'm not too familiar with co-op but it looks like only 4 player would benefit from an offset, and at that point I think moving descriptions down at all might be infringing on P3's space anyway

**Comment by Ma-rcx** [comment]
> I'm not too familiar with co-op but it looks like only 4 player would benefit from an offset, and at that point I think moving descriptions down at all might be infringing on P3's space anyway

Disregard this, I thought co-op was similar to J&E, but I remembered wrong. Tested just now and nothing should overlap.

**Comment by wofsauge** [comment]
Buurazu fixed the mentioned offsets now. thanks for the report and the fix ;)
