### ISSUE TITLE
Not really an issue sorry

### ISSUE THREAD

**Issue by Lutin7** [wofsauge/External-Item-Descriptions#379]
Hi all i dont use steam for this game. I'm on [Repentance V4.0.2] could someone help me to install this mod on it ?
Thanks to any answer

**Comment by AutisticGoat** [comment]
For the next question on the Discord server please
I'm afraid you can't install mods in version 4.0.2, mods support came in 4.0.4 (or 1.7.4), currently we are on 1.7.7 (or 4.0.7)
