### ISSUE TITLE
Change description by checking characters name

### ISSUE THREAD

**Issue by mmp1982** [wofsauge/External-Item-Descriptions#393]
self-explanatory
![image](https://user-images.githubusercontent.com/52797647/156057257-870e8a0f-c31a-46a9-b0ea-abed758bb567.png)

**Comment by Buurazu** [comment]
Localization support makes this sort of find+replace harder than it seems, and multiple items have Isaac in their name so there could be false positives
also lore says they're all isaac (mom says isaac!)

**Comment by mmp1982** [comment]
oh alright then!!
