### ISSUE TITLE
Dynamic names

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#399]
Basically a way to generate names like the {{CollectibleXX}} tag, so descriptions can refer to items and other elements in the user's chosen language. Would need to support items, trinkets, rooms, enemies, bosses, curses, slot machines and beggars as well as individual strings like "devil deal" for example. Would be nice if generated names supported colors as well.

Example:

"Triggers the effect of {{NameC3}} or {{NameT127}} when fighting {{NameB45}}"
would output
"Triggers the effect of Spoon Bender or Baby-Bender when fighting Mom"

**Comment by wofsauge** [comment]
Added first implementation of this Feature with Commit [b60439b](https://github.com/wofsauge/External-Item-Descriptions/commit/b60439bddcce3af0a7691bc8bade6cb4eaabcf13)

Examples:
{{NameC3}} -> Spoon Bender (C = collectible)
{{NameT23}} -> Missing Poster (T = trinket)
{{Name5.100.231}} -> Ball of Tar (generic Entity name)
Other markup: K = Card, P = Pill

**Comment by wofsauge** [comment]
Feature is now fully implemented. Thank you for the request :)
