### ISSUE TITLE
Markup display settings(Icons only, text only, etc)

### ISSUE THREAD

**Issue by kohashiwakaba** [wofsauge/External-Item-Descriptions#407]
While testing with small icons from #405 There were some suggestions with markup icons. Currently Korean translation shows both icons and markups such as
`{{Damage}}Damage up`
Some people from community asked me to toggle stats icons, like 'show only names' `Damage up`
or
'show only markups' `{{Damage}}`
(yeah, both were in suggestions).

'show only names' was directly referenced from #287, but the problem goes to 'show only markups', since showing only markups from most items could be a lot awkward, like short words with lots of empty lines, moreover, this has a lot problems with managing with many languages, especially, I'm guessing this is not possible for English

Also, apart from suggestions above, I'd wish the toggle for icon sizes for some markups, making `{{Damage}}` to `{{DamageSmall}}`, and vice versa.

**Comment by wofsauge** [comment]
Toggle to switch between big and small icons was added a while ago. but i dont think that a toggle for "icon or Text only" will be added anymore, since i dont see a practical usecase to disable helpful informations and visual indicators.

If the topic is still relevant, please open a new issue :)
