### ISSUE TITLE
Add new markup for en_us translation

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#410]
Spanish and Korean added cool new markup icons for their descriptions. Now we should add those to the English language as well. For example the stat change icons, curse icons, status effect icons etc.

**Comment by AutisticGoat** [comment]
I have added all the markups that I have seen that could be added, I will keep checking the English descriptions to see if I can find more things to add

**Comment by wofsauge** [comment]
nice work! thanks for doing it :)
