### ISSUE TITLE
Workshop mod description per language?

### ISSUE THREAD

**Issue by kohashiwakaba** [wofsauge/External-Item-Descriptions#437]
Recently, EID had accepted, and merged several language packs into single mod. But still mod description only shows English, which lead some people use outdated or separated version.
Of course, the mod developers of separated version adds instruction to use original EID, but some people eventually use separated version, mainly because the original EID mod doesn't show their native language, or most people don't even read mod description. (EID does NOT even show in search results when people inputs mod name for their languages)

Thankfully Steam workshop has a function that show description per language, shown as below.

![wakaba_2022_03_30_204246_1648640566](https://user-images.githubusercontent.com/37092106/160826847-cc60418a-9414-446e-95fa-2f097b355747.png)

The main downside is only people marked as creator shown in mod(Wofsauge, fly_6 in current state) can edit mod description AFAIK, and updating the mod through Mod Uploader only updates English description.

**Comment by AutisticGoat** [comment]
I suppose that each translator could rewrite the EID description to their own language and then Wofsauge or fly_6 could add them to their respective language

**Comment by wofsauge** [comment]
Ive added a mod description for Korean now. If someone wants to provide a translation for another language, just send them to me :)
