### ISSUE TITLE
Investigate double rendering of EID in water rooms

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#438]
render callbacks are called twice when in water filled rooms, you can just lock the water rendering behind this statement:
Game():GetRoom():GetRenderMode() ~= RenderMode.RENDER_WATER_REFLECT

We need to investigate if eid is rendered twice per frame in such rooms. If thats the case, we need to prevent that

**Comment by Buurazu** [comment]
Doing a print in main.lua's onRender only shows 1 trigger per frame, with render mode 0, while in Downpour
I don't know if there's something more to it than that

**Comment by wofsauge** [comment]
Investigated: it does not occur for us, so no action needed
