### ISSUE TITLE
Sacrifice room payout display bugs out when Glowing Hourglass is used

### ISSUE THREAD

**Issue by SiwwiSiwwi** [wofsauge/External-Item-Descriptions#463]
Whenever you use a sacrifice room and then use glowing hourglass, the sac room payouts reset, but the counter on the display does not. 
EXAMPLE: I used the sacrifice room some, didn't like the payouts, and used glowing hourglass. When I went back in, the display for the next reward did not reset to 0.
![image](https://user-images.githubusercontent.com/105602016/168484992-da567b26-213c-4e56-8bc9-462f9ae3a9a1.png)

**Comment by Buurazu** [comment]
I've added support for rewinding our vars upon Glowing Hourglass usage. Right now, sacrifice counter is the only thing there, but I'm sure there's some other vars we might want to rewind, so I made sure it's open-ended.
