### ISSUE TITLE
Void stat prediction uses glitched item text for tears

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#480]
The bit that tells you what stats are going to be increased by voiding an item uses the text intended for glitched items for the tears stat.
Example:

![image](https://user-images.githubusercontent.com/73142552/173982726-f1ea0618-a966-42c0-99ad-d714ed0f9194.png)

It should use this string :
![image](https://user-images.githubusercontent.com/73142552/173982751-9362f78f-e693-4b9b-be92-8b0e69e4aaa5.png)

But it uses this one : 
![image](https://user-images.githubusercontent.com/73142552/173982914-c7484d85-f787-4625-b9bc-c808036d2d76.png)

(I changed the text to GLITCHEDITEMTEARS for the purpose of this bug report so it is clearer)

**Comment by Buurazu** [comment]
Hmm, I guess I originally reused the "Fire Rate" from glitched text instead of having a separate thing to localize, but then changed my mind and added a VoidNames override to rep's file, but didn't change the code. Thanks.

**Comment by biobak64** [comment]
@Buurazu Ah i see, makes sense. If you're taking a look at this, would you mind allowing translators to change the void stats syntax? The rest of my localization has stats numbers after the stat name (damage +1 instead of +1 damage) and it would be nice to be able to keep it coherent (like you can for glitched items). Thanks a lot

**Comment by Buurazu** [comment]
Hmm ok. Is "{1}" still fine as the signal for a +/- number replacement to occur? (like "Speed up {1}" becomes "Speed up +0.2")

**Comment by biobak64** [comment]
sure, sounds good to me! that also makes it so you can color the number which is nice

**Comment by Buurazu** [comment]
OK, {1} replacing will be in the next update, and I'll keep it in mind for the future of item prediction features
