### ISSUE TITLE
Mod Config Menu>Crafting tab, when without the bag, shows descriptions of item pedestals on the ground.

### ISSUE THREAD

**Issue by TrainerX493** [wofsauge/External-Item-Descriptions#488]
As Tainted Cain (who of course has the bag of crafting), the "Crafting" tab shows the recipe as expected when there's enough pickups for the bag available. And otherwise shows no overlay, even when next to a pedestal.

But if you are playing a character without the bag, the Crafting tab will instead show the description for any nearby item pedestal within range.

It should also be noted that moving from the "Crafting" tab to the "Save Game" tab will keep the overlay on the screen shown (with or without the bag), when it should be hidden.

**Comment by wofsauge** [comment]
This got fixed now with commit 2743474
