### ISSUE TITLE
Modeling clay item reminder/ prediction

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#509]
If the Modelling Clay is in the trinket slot or if it's gulped, holding TAB (AKA the key that displays info about held items and consumables) will also display the effect of the item copied by the clay. This would be especially useful if the trinket is gulped because normally, in these circumstances, you cannot see what item it copies.

**Comment by Buurazu** [comment]
since there's an api function specifically for the modeling clay, it should be trivial, same goes for what item Zodiac is
but should seeing its item form when its gulped count fall under the "show hidden info" option?

**Comment by wofsauge** [comment]
Added Modeling Clay support with commit dc13324e030cb603e11895f0bc36938e04bbb54c
added Zodiac Support with commit 27c7b9ceb1e73401480bea1d0a54fbffc77c3eee
