### ISSUE TITLE
item descriptions will not display

### ISSUE THREAD

**Issue by Donny-Simmonds** [wofsauge/External-Item-Descriptions#52]
Recently grabbed the newest update, however none of the item descriptions are showing up.  I've tried unsubbing/resubbing, playing with the config in mod-menu, editing config in the local files setting most things to true, and I've mashed the F2 button relentlessly but to no avail.

**Comment by wofsauge** [comment]
@Donny-Simmonds Can you take a look into the debug console and see if it displays any error messages? 
Here is the info on how to open it ingame: https://bindingofisaacrebirth.gamepedia.com/Debug_Console

**Comment by wofsauge** [comment]
send a screenshot of the errors if there are any, please :)

**Comment by Donny-Simmonds** [comment]
For sure, here's the little bit of information in there.  Seems to be there's some missing files somewhere

https://imgur.com/a/N4e8esM

**Comment by wofsauge** [comment]
hmm i just tried it myself and the file that is missing in your case is definetly in the currently uploaded version. Everything works as it should.
i suspect that some of your game files are maybe corrupt, so first, try the run the "Verify integrity of game files..." function of steam: https://inxile.zendesk.com/hc/en-us/articles/115004662908-Verify-game-cache-files-Steam-

after that, unsubscribe from the mod. start the game, close the game after going on the main menu screen, subscribe to the mod again and start the game again to try it.

hopefully this fixes your issue.

**Comment by Donny-Simmonds** [comment]
Looks like that fixed the problem.  Verified well, followed your instructions and I tried to load my save but it crashed.  After I started a new game it worked like it should.  I wasn't getting any of the example text from the menu showing up either, now that I have it working again I noticed.

**Comment by wofsauge** [comment]
glad to hear that. Have fun with the mod :)

**Comment by hui693** [comment]
External item descriptions isn't working, I have the cracked version, however every other mod works just fine.

**Comment by epfly6** [comment]
> External item descriptions isn't working, I have the cracked version, however every other mod works just fine.

What's game version?

**Comment by Buurazu** [comment]
If this "cracked" version is actually the DRM-free GOG version, it doesnt support mods
enable the debug console and see what error it says

**Comment by hui693** [comment]
v1.7.7

**Comment by hui693** [comment]
buurazu i have the debug console enabled but what am i looking for exactly bc when i open it in game i cant see any errors

**Comment by hui693** [comment]
and the way i use mods is i go to steam copy the link, paste it in steamworkshop downloader after that i download and extract put it in the mods folder and then in data

**Comment by Buurazu** [comment]
Try going near an item then
If EID is enabled in the main menu mods list, but descriptions aren't showing when near an item, there should be errors in console at that point, or you just have descriptions disabled/hidden

**Comment by hui693** [comment]
there isn't an error and how do i turn the descriptions on

**Comment by Buurazu** [comment]
by default, F2 toggles descriptions on and off
if you have Mod Config Menu you can see if EID is on in there

**Comment by hui693** [comment]
do i press f2 in game

**Comment by hui693** [comment]
do u have a dc?

**Comment by Buurazu** [comment]
yes https://discord.gg/AuUShrZaYC

**Comment by hui693** [comment]
yup i joined
