### ISSUE TITLE
Transformation tracker : Need to track all items instead of actives only

### ISSUE THREAD

**Issue by kohashiwakaba** [wofsauge/External-Item-Descriptions#522]
Transformation tracker does not track correctly, mainly after using D4.
Using Full Reroll(D4) completely loses all transformation progress, but tracker does not track this properly.

To be exact, **all passives** that granted by full reroll doesn't count as transformation progress at all, as they aren't count as 'first pickup'.

Rerolling actives that currenly holding through 1-pip dice room also loses transformation progress.

Thus, we need to track all items instead of only actives.

Made this issue to remark (even though that it is discussed before in Discord) because many Korean players reported this bug for long time.

**Comment by wofsauge** [comment]
This issue should be fixed now with commit 8a2dbebbbe50adca7ac455afc62c77780d75ada8
Thanks for the report :)
