### ISSUE TITLE
SaveGame attempt to index a function value

### ISSUE THREAD

**Issue by tjquillan** [wofsauge/External-Item-Descriptions#529]
As of mod version `4.44` and `4.45` this mod throws the following error:
```
[INFO] - [External Item Descriptions] Error in "PostRender" call: ...th/mods/external item descriptions_836319872/eid_api.lua:1542: attempt to index a function value (field 'SaveGame')
```

After doing some looking around I suspect it is related to https://github.com/wofsauge/External-Item-Descriptions/commit/a58163db3ab94e2d7b341a3ddd5a9a9f90ce5ddd in which the `SaveGame` function was changed to `EID:SaveGame` which I believe clashes with `EID.SaveGame` which is acceced as a table as shown below:
https://github.com/wofsauge/External-Item-Descriptions/blob/4ed0d3fa0aa6ff58bf15c0414850496f5d3ddcad/eid_api.lua#L1541
https://github.com/wofsauge/External-Item-Descriptions/blob/4ed0d3fa0aa6ff58bf15c0414850496f5d3ddcad/eid_api.lua#L1542
https://github.com/wofsauge/External-Item-Descriptions/blob/4ed0d3fa0aa6ff58bf15c0414850496f5d3ddcad/eid_api.lua#L1548

I am not super framiliar with Lua so these are only my best guesses. Hope this is helpful!

**Comment by Buurazu** [comment]
That's very silly, I've renamed the function to SaveTheGame which should fix it.
I'm guessing you have the "show items needed for collection" stuff turned on? The error might only happen if you do, so it didn't get caught.
