### ISSUE TITLE
Suggestion: Display warning when strong items "trump" each other

### ISSUE THREAD

**Issue by csuhta** [wofsauge/External-Item-Descriptions#542]
First: Thank you for all the work you do on this mod.

It would be nice to see warnings shown when items do not combo at all (not bad synergies, actual replacements). Especially for strong or 4-star items that are difficult to obtain. These kinds if interactions still have to be looked up elsewhere. This is most critical for wholesale tear replacement items. For example:

- [Brimstone](https://bindingofisaacrebirth.fandom.com/wiki/Brimstone) completely overrides [Trisagion](https://bindingofisaacrebirth.fandom.com/wiki/Trisagion)
- [Mom's Knife](https://bindingofisaacrebirth.fandom.com/wiki/Mom%27s_Knife) overrides [Jacob's Ladder](https://bindingofisaacrebirth.fandom.com/wiki/Jacob%27s_Ladder)

Show a warning when an item is going to completely replace another.

**Comment by Buurazu** [comment]
"Overrides" and "Overridden by" add-ons to descriptions will be getting added very soon with the new conditionals system
