### ISSUE TITLE
Little Baggy Description

### ISSUE THREAD

**Issue by adamthedog** [wofsauge/External-Item-Descriptions#55]
Says "Replaces all pills with cards" but should be the other way around ("replaces all cards with pills").

**Comment by wofsauge** [comment]
The reported issue cant be reproduced. the description is correct for both "little baggy" and "Starter Deck"...

![image](https://user-images.githubusercontent.com/245725/103789337-2f805280-5040-11eb-8952-32205a09fd31.png)
