### ISSUE TITLE
eid_api.lua:310: bad arguments #2 to 'Load' (string expected, got no value)

### ISSUE THREAD

**Issue by ArliArdevlirn** [wofsauge/External-Item-Descriptions#552]
The mod is not working, debugconsole show this error:
eid_api.lua:310: bad arguments #2 to 'Load' (string expected, got no value)

PS: Decided to try fixing it myself, since the documentation doesn't mention any 2nd argument for the font:Load() function and the error thrown want a 2nd argument being a string i added a "test" string as second argument to see what error would be thrown and get a clue of what is expected from this argument. Turn out just adding "test" as 2nd argument doesn't throw any error and allow the mod to work properly.

**Comment by epfly6** [comment]
Hi, something to confirm. Are you playing the GoG version of the game or the Steam version?

**Comment by ArliArdevlirn** [comment]
GoG version of the game, Also i do not have the Repentance DLC.

**Comment by epfly6** [comment]
I knew it. Someone messed up some tech stuff for Lua in GoG version. If you pass second string as you mentioned, it should do the trick and fix Load function

**Comment by wofsauge** [comment]
Fixed with commit [7a74260](https://github.com/wofsauge/External-Item-Descriptions/commit/7a74260e549fe0346fee276efe4caf80cea4e30e)
