### ISSUE TITLE
Suggestion: Some sort of loading bar for when the bag of crafting is calculating the recipes.

### ISSUE THREAD

**Issue by mari-does-not-dream-of-mental-stability** [wofsauge/External-Item-Descriptions#557]
I think an loading bar for when the bag of crafting is calculating the recipes would be pretty nice since it can take quite a while for it to finish calculating them. Also if you're in the angel/devil room waiting without doing anything since if you exit you will lose the pickups nor knowing how much time it's going to take is pretty bad.

**Comment by Buurazu** [comment]
I'd just suggest lowering the settings for recipe generation, that's what the settings are there for.

**Comment by wofsauge** [comment]
wont do. As Buurazu said, the recipe calculator performance can be altered by changing the config options "BagOfCraftingCombinationMax" and "BagOfCraftingRandomResults".
