### ISSUE TITLE
Make Tarot Cloth descriptions like Golden Trinket descriptions

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#563]
Right now, the descriptions of cards affected by Tarot Cloth display the normal card description first, then the doubled version, unlike golden trinkets which display only one description with the increased numbers in a gold font. For consistency and conciseness, i think doubled card effects should be displayed like this instead.

**Comment by Buurazu** [comment]
I agree, also for co-op I think it'd be nice if it showed the regular description and then the tarot cloth one with like the "Character Name" line separating the two, like pills
