### ISSUE TITLE
Update Glowing Hourglass description when it is depleted

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#564]
When Glowing Hourglass temporarily becomes The Hourglass, its description doesn't change. I've seen multiple (new) players be confused about the effect of the item when the sprite changes, so it would be nice to have the description change to that of The Hourglass and add that it will become Glowing Hourglass again when the next floor starts

**Comment by wofsauge** [comment]
Info:
The glowing hourglass is depleted, when the ActiveItemDesc.VarData variable is set to 3. its 0 on default and increases by one for each lost charge.
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/245725/eeaa2c41-bba9-45d3-8b24-7af2c13f9219)
