### ISSUE TITLE
I need the latest version for 1.7.8

### ISSUE THREAD

**Issue by StentMan** [wofsauge/External-Item-Descriptions#569]
This is just a support question/request, sorry. I probably posted this in the wrong place.

Unfortunately for me, I got the game from GOG where it did not get updated to 1.7.9, so I need someone to point me to the latest version of this indispensable mod that matches my game version.

My best guess is v4.46, so if someone could confirm, or even better, clearly label the release - that would be awesome.

**Comment by StentMan** [comment]
OK, My initial guess was wrong, it appears that v4.42 is the latest that doesn't show the warning about not being the latest (1.79) version.

**Comment by wofsauge** [comment]
yes, v4.42 is the latest version for 1.7.8

Ive updated the descriptions for the last 20 releases that include this version and the 5 before that. All releases up from v4.35 now contain the version of the patch, and if its the last compatible release, it contains a huge text that tells you that fact.

Thanks for the feedback :)

**Comment by StentMan** [comment]
> yes, v4.42 is the latest version for 1.7.8
> 
> Ive updated the descriptions for the last 20 releases that include this version and the 5 before that. All releases up from v4.35 now contain the version of the patch, and if its the last compatible release, it contains a huge text that tells you that fact.
> 
> Thanks for the feedback :)

Thank you!
