### ISSUE TITLE
The most recent version of the mod can be install on new iOS repetance version?

### ISSUE THREAD

**Issue by ArturoGallardoR** [wofsauge/External-Item-Descriptions#622]
I wonder if is possible to put this mod on the iOS version of repetance?
Thx!

**Comment by wofsauge** [comment]
No. The ios version requires you to install the rebirth version of the mod. Here is a tutorial on how to do that:
https://github.com/wofsauge/External-Item-Descriptions/wiki/How-to-install-the-mod#ios-rebirth
