### ISSUE TITLE
[Rebirth]Objects such as rocks and campfire logs block the item description text

### ISSUE THREAD

**Issue by xecus922** [wofsauge/External-Item-Descriptions#625]
![20231226105724_1](https://github.com/wofsauge/External-Item-Descriptions/assets/35088630/1dd07315-8920-42f7-ba37-fe5a9974deb4)

Just installed the mod, wanted to give it a try, got sick of constantly alt-tabbing to the wiki page then I noticed this happening. 

I was hoping F2 would toggle the mod on/off to hopefully replace the position of the item description but that hotkey doesn't seem to do anything.

**Comment by wofsauge** [comment]
thats not fixable since the rebirth version of the game does not provide a modding api for the game that is as capable as the one added with ab+/repentance.
