### ISSUE TITLE
EID does not work properly with Bag of Crafting on tainted Cain

### ISSUE THREAD

**Issue by Ozyrys500** [wofsauge/External-Item-Descriptions#626]
Exactly as in the title, the EID does not work properly with bag of crafting, to be precise it does not show correct recipes for the items half the time. I could have EID show me that the item I'm gonna craft is gonna be experimental treatment, but the bag itself will show me a robo baby (this is an example that I had). I play with mods but most of the ones that I use are purely visual, the only ones that might be adding some new items are "ancient revelation", "Samael" and "Mei" mods, and there are 2 mods which obstruct spawning of 2 items, those two being "no more taurus" and "no more breakfast", rest of the mods I use are pure cosmetic kind.

**Comment by wofsauge** [comment]
this issue is caused by any modded item added to any itempool. The issue can only be fixed by using REPENTOGON. we will soon work on a solution in that regard.

**Comment by Ozyrys500** [comment]
So I did install REPENTOGON, but it still shows the wrong items. Is there something special that needs to be done EID to start working using that mod?

**Comment by wofsauge** [comment]
As mentioned previously, we are still working on the feature. It is not finished and therefore can't work as of right now...

**Comment by The-furf-of-July** [comment]
So this is not completed, but a work-in-progress feature?
