### ISSUE TITLE
Suggestion: Avoid "Home" Spoilers

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [wofsauge/External-Item-Descriptions#627]
Some item descriptions say "opens the door to Home" and things like that, such as Faded Polaroid and Broken Lock, or Dad's Note. As of now, this spoils the existence of Home to new players, aside from being technically wrong as that's the door to Mausoleum II. These could be changed to "Opens a/the strange door," the name that the mauso II door is given when beating Mother for the first time in the achievement popup. Experienced players who havent seen the popup in a while will more than likely already know this information about the items, novice players who have just seen the popup recently will know what it's talking about, and "a strange door" is vague enough to not spoil anything at all to new players. As for Dad's Note, simply changing the description to "begins the Ascent" while keeping the info about trinkets being turned to keys will make the ascent more exciting as you are left to wonder what happens when you ascend past Basement I, instead of being blatantly told about Home.

**Comment by ruguysgoingtrickortreating** [comment]
#476 could work too

**Comment by ruguysgoingtrickortreating** [comment]
My bad, Dad's Note already says "begins the ascent"

**Comment by wofsauge** [comment]
Thanks for the report. I tried to rephrase those descriptions to be less spoilery
