### ISSUE TITLE
Experimental Pill showing conflicting stat description

### ISSUE THREAD

**Issue by dbolger** [wofsauge/External-Item-Descriptions#633]
Experimental Pill by default shows that there's no stat increase with False PHD. When a character has False PHD, the 0.6+ Damage indicator shows.
Perhaps the 0.6+ Damage indicator should be removed if the pill is an experimental pill?
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/37427166/2d162546-a2e2-4bf9-a015-650f49823e56)

**Comment by dbolger** [comment]
Ah I think I misinterpreted how this should read. In reality I think the stat increase at the top would not apply, so conditionally we wouldn't want to show the top line and only the decrease random stat and the damage up from taking a pill while having False PHD.

**Comment by Buurazu** [comment]
Will be changed in the next update.
It will be a modifier that checks each player for what text they need (and specifies "No random stat increase" for false phd)
Conditionally removing lines is trickier and not co-op friendly so appending a line is fine imo
