### ISSUE TITLE
Newest update broke it (v 4.68)

### ISSUE THREAD

**Issue by ReasonFoundDecoy** [wofsauge/External-Item-Descriptions#641]
Doesn't show item descriptions, oops

**Comment by wofsauge** [comment]
can you look into the debug console and tell me the error messages you get?

**Comment by ReasonFoundDecoy** [comment]
...xternal item descriptions_836319872/eid_conditionals.lua:108: attempt to index a nil value (global 'Achievement')

**Comment by wofsauge** [comment]
the issue should be fixed now. to force steam to install the newest version of the mod, please do the following:

1. close game
2. unsubscribe form the mod
3. start game and enter the main menu
4. close game
5. subscribe to the mod
6. start game
7. continue your run

**Comment by ReasonFoundDecoy** [comment]
it works! thanks for such a quick fix :)
