### ISSUE TITLE
Wrong Floor Item count in Tainted Cain Crafting Menu

### ISSUE THREAD

**Issue by marco3102** [wofsauge/External-Item-Descriptions#642]
Found this. 
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/116598674/6f9c683c-ab25-4034-ae0e-66d8746728cb)
The Floor Pickup Count is wrong. I checked every Room. Boss Room is Dad's Note and was empty.
 
Here are my mods:
https://drive.google.com/file/d/12ZbwEop0jY6vEhVWNtNcTHvJwfEvI5xS/view?usp=sharing

**Comment by wofsauge** [comment]
this issue was fixed with commit 01788b0d11f19ebff508530ddaf7f83b598040c0

The fix requires repentogon to work
