### ISSUE TITLE
Suggestion: Display wisp effects from current active item when Book of Virtues is in the room 

### ISSUE THREAD

**Issue by duncathan** [wofsauge/External-Item-Descriptions#645]
In situations where a resource must be spent to pick up Book of Virtues, it would be handy for EID to display the current wisp effect when display BoV's description. It's otherwise very tedious to find out, or requires spending the resource to just grab the book.

This would also address an annoyance I have which the BoV description and my active item's description are both so long that even after picking it up I can't see the wisp info because the text goes off screen, though I understand other solutions for that are in the works as well

**Comment by duncathan** [comment]
Perhaps the existing condition for displaying the wisp effect (which I believe is just holding BoV) could be changed to either holding it OR simply having it visible in the current room/screen?

**Comment by magagnato4106** [comment]
Do you mean a sort of GIF of what the wisp does? Too difficult imho. Maybe something like the exact wisp image because most of the effects written by BoV is actually understandable

**Comment by duncathan** [comment]
a GIF? no, I'm just talking about displaying the text that already exists when you're holding BoV and standing near an active item

**Comment by magagnato4106** [comment]
Ah ok. But at the end you could just pick up at that point because if you find something better you just switch it and you can also see the effect. Otherwise well another feature to solve

**Comment by duncathan** [comment]
Yes, this is a feature request. There are many situations where picking up the item to check its wisp effect is undesirable: boss challenge rooms, there's options/more options dual pedestals, angel/devil rooms, etc. so "you might as well pick it up" really isn't an ideal solution

**Comment by wofsauge** [comment]
Feature got added some time ago with commit e810082. closing issue
