### ISSUE TITLE
Wrong description for Golden Mom's Kiss

### ISSUE THREAD

**Issue by magagnato4106** [wofsauge/External-Item-Descriptions#651]
The description for Golden Mom's Kiss is wrong or is either not complete. In fact, if picking it up when playing T Keeper it will give 2 coin heart container and not just one (only maybe for Keeper?). I report this because it misleads in any case when playing T keeper rather than normal Keeper
<img width="960" alt="BugIsaac" src="https://github.com/wofsauge/External-Item-Descriptions/assets/46919277/5306fd29-1975-489c-81cd-e81981856845">
<img width="960" alt="BugIsaac_1" src="https://github.com/wofsauge/External-Item-Descriptions/assets/46919277/cc1b17af-5cee-494b-83f6-c59d2e5ee0a4">
.

**Comment by Buurazu** [comment]
It was an oversight, will be fixed next update
