### ISSUE TITLE
Wrong craft display in the craft bag

### ISSUE THREAD

**Issue by JustJabka** [wofsauge/External-Item-Descriptions#657]
I have for some reason some of the crafts are displayed wrong: for example, I tried to craft "C Section", but I got "Options?" on the output. Even though I have "C Section" unlocked.

![20240506202611_1](https://github.com/wofsauge/External-Item-Descriptions/assets/117545035/f804a522-bcac-4c09-ac3c-5a75f7c12290)
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/117545035/e9604fe0-f459-46e1-842b-8e03d02775ec)

I don't have any mods that add new items. Here's a list of mods: https://steamcommunity.com/sharedfiles/filedetails/?id=3240990722

**Comment by JustJabka** [comment]
Thanks, do I need to send the save file from Steam/userdata/250900 or from user/documents/My Games/Binding of Isaac Repentance?

**Comment by wofsauge** [comment]
the steam userdata one please

**Comment by JustJabka** [comment]
[remote.zip](https://github.com/wofsauge/External-Item-Descriptions/files/15225478/remote.zip)

**Comment by wofsauge** [comment]
hey. 
The save files worked well. thanks for providing them.
We made a few changes to the bag of crafting code, and it seems like i am no longer able to reproduce the issue with your save file. Therefore it seems to work for me with repentogon now.

Can you maybe check if the issue still persists?

**Comment by JustJabka** [comment]
Hi, I checked, the issue is gone, thank you very much

**Comment by wofsauge** [comment]
Awesome! Thanks for testing :)
