### ISSUE TITLE
remove detailed descriptions

### ISSUE THREAD

**Issue by Mirades** [wofsauge/External-Item-Descriptions#665]
Since the regular descriptions are getting more and more detailed, and the detailed version is very outdated for some time now, i suggest we just remove it, because there might be some users that think it's a more detailed version, which it clearly is not at the moment. And it doesn't seem to be in the near future.

**Comment by Buurazu** [comment]
I was thinking the same thing a few weeks ago, either it needs deleting or updating (like some kind of auto-text-pull from the wiki)
I'd feel bad for anyone using it

**Comment by magagnato4106** [comment]
My personal opinion is that it needs to be removed: with the different implementation of BFFS!, Car Battery, BoV, etc... synergies I think it gives everything needed in the shortest amount of character. Other than that, it could only be something more peculiar that could be added like conditionals (that @Buurazu is already working on)

**Comment by wofsauge** [comment]
English Detailed languagepack got removed now
