### ISSUE TITLE
Indicator for Item Quality

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#67]

**Comment by Mrashes** [comment]
@wofsauge I'm willing to help out if you'd like.  I imagine this ticket might be a good way for me to get started.  Most of my background is JS/TS and Bash but wanted to have a side project to work on.

**Comment by wofsauge** [comment]
Help is always appreciated of course :)

The problem with this issue right here is just, that the current modding API does not include Repentance specific content. Therefore, the access to the Quality information is currently not possible without a lookup table (which i want to avoid). 
Thats why the issue has to wait a bit for the next patch of the game :)

**Comment by Mrashes** [comment]
Alright, when the patch comes out I'll reach out to you.   Thanks!

**Comment by wofsauge** [comment]
@Mrashes If you still want, you can implement this feature now :)

**Comment by Mrashes** [comment]
Alright, first Lua thing so let me take a look.  sorry for the delay
