### ISSUE TITLE
Bug in the Inventory Overview

### ISSUE THREAD

**Issue by magagnato4106** [wofsauge/External-Item-Descriptions#671]
Hi. I don't know why but I found this sort of particolar bug in the inventory overview. It finds an item that I don't have. I don't know if it was due to 3 dollar bills effect or it didn't clear the previous run. I know only that is kinda strange

<img width="960" alt="BugInventory" src="https://github.com/wofsauge/External-Item-Descriptions/assets/46919277/b9c9fa20-8ae8-40e5-bc83-93ca7b8581c2">

(Of course it doesn't cycle when 3 dollar bill change tear effect)

**Comment by Buurazu** [comment]
Yeah, it is some bug with temporary effects; it's quite odd as it adds the first effect you get from 3 dollar bill to the reminder, but then never removes it or updates it

**Comment by wofsauge** [comment]
This issue should be fixed now. A followup issue for 3 dollar bill effect is created
