### ISSUE TITLE
Greed conditionals + Car Battery info before picking when having an item

### ISSUE THREAD

**Issue by magagnato4106** [wofsauge/External-Item-Descriptions#674]
Hi! Playing Greed isn't like playing a normal run in Isaac: it's a different mode where certain item lost or gain a lot of value. For example, Champion Belt is only a 1 damage up since champions drop do not exist or also The World is useless or even The Moon teleports to the Super Secret Room rather than the normal secret room.

Also sometimes I go into Car Battery with an active item but I don't know if it's worth picking in up with the current active item: is it possible to add this kind of feature (like done with BoV sometimes ago)?

**Comment by Buurazu** [comment]
Champion Belt does what it says in Greed mode, doesn't it?
Changing those card effect texts for Greed mode sounds good.
I'm working on the Car Battery conditional right now and might add a data table for items with no effect from it, and that could easily be applied to both the active's desc and Car Battery's desc. I probably won't add a line if Car Battery just doubles the active as expected, it's common sense.

**Comment by magagnato4106** [comment]
That's perfect: do you think it's possible to do a sort of "danger items" list for Greed item? I know there's a wiki page in the fandom that tells about items that are kind of 💩  in greed.

**Comment by Buurazu** [comment]
I don't think we have too much opinion about shit items in EID, and Champion Belt in Greed Mode definitely wouldn't qualify in my book if we did, it does what it says on the tin... right? Looking at that wiki list it says Champion Belt quadruples champion spawn chance? If that's the case rather than +15%, and only in Greed Mode, then it could get an addendum. I'll definitely look into adding a Greed addendum to an effect like Blanket, Mama Mega, Deep Pockets.
Total run killer item combos could also start getting added as conditionals now if you have any ideas, if they're really bad.

**Comment by Buurazu** [comment]
Oh wait, I see, the +15% is going from 5% to 20%. Maybe the wording on Champion Belt should be changed in general to make it more clear it's quadrupling the chance, I forgot the change is that huge.

**Comment by magagnato4106** [comment]
> I don't think we have too much opinion about shit items in EID, and Champion Belt in Greed Mode definitely wouldn't qualify in my book if we did, it does what it says on the tin... right? Looking at that wiki list it says Champion Belt quadruples champion spawn chance? If that's the case rather than +15%, and only in Greed Mode, then it could get an addendum. I'll definitely look into adding a Greed addendum to an effect like Blanket, Mama Mega, Deep Pockets. Total run killer item combos could also start getting added as conditionals now if you have any ideas, if they're really bad.

Wait but Champion Belt does provide the damage up but increases the spawning chance of Champions in the arena but without the utility of champions drops. I think this is the kind of "warning" that it needs to be displayed (a part from the wording of Champion Belt itself) in my honest opinion! There aren't a lot of them, but some infos about them can always be useful.

**Comment by Buurazu** [comment]
I'm working on Greed stuff now. In my testing, The Moon just acts as The Fool in Greed Mode, but I'm also wondering if it spawns at all? I can't find anything about certain cards being blacklisted in Greed Mode but I don't think I've ever used one.

**Comment by magagnato4106** [comment]
Every card can spawn in Greed and yes I can assure you this because I find one in a Greed run

**Comment by Buurazu** [comment]
Well, The Moon definitely just warps me to the starting room on both AB+ and Rep, not the Super Secret Room; maybe you have a mod that changes it?

**Comment by magagnato4106** [comment]
Nono I know it doesn't teleport you in the secret room! In fac,t the card tells you that it teleports you to a Secret Room in Greed, but actually in the Greed mode, the secret room is a Super Secret Room: so it acts as a "The Fool" but the description tells you that it teleports you to the Secret which isn't true or well it's true but there are no Secret rooms in Greed.

I was stupid I forgot to say that it doesn't teleport you at all: I wrote the sentence but with incomplete parts. I'm in shambles for the stupid comment on that part

**Comment by Buurazu** [comment]
Oh ok. I bought like 50 cards and didn't find one but I'll change the desc anyway, no harm in it.

Currently my greed modified descs are:
Temperance, The Sun, The Moon, The Moon?, Blanket, Mama Mega, Deep Pockets, Match Book
No effect descs are:
Guppy's Tail, Contract from Below, Glyph of Balance, The World, Cain's Eye, Store Key, Rib of Greed, Karma, Fragmented Card, Silver Dollar, Bloody Crown, Door Stop

Probably will modify the room clear trinkets (that are nogreed tagged in rep) as well, they aren't useless but they only increase payouts from chests.

Any more suggestions?

**Comment by magagnato4106** [comment]
Treasure map no effect, The Mind useless if you have already Blue map, Blue Map acts like a The Mind. Red Key does work in Greed and how? Other than that, I don't know if other items or trinkets do not have effect in Greed/Greedier.

**Comment by Buurazu** [comment]
Alright, I've added those, plus some more, as greed mode conditionals.
I also have it so Car Battery and BFFS pedestals will say if you have a "no effect" item. I plan on expanding that to whitelisting certain synergies (esp. negative ones) to show up on a Car Battery/BFFS pedestal as well if they're interesting enough, as well as making sure characters like TEve/TApollyon/TLilith/Lilith get a conditional on BFFS since BFFS is such a huge boost for them specifically.

**Comment by magagnato4106** [comment]
Sorry maybe I've mispelled it in the title, but is it possible to have a sort of info of what the active item does when picking car battery? So when I find it in the shop I know if it's worth the cash or not?

**Comment by Buurazu** [comment]
For 99% of them that aren't "no effect", it uses it twice, self-explanatory... Are there any actives in particular you have in mind?

**Comment by magagnato4106** [comment]
I don't remember if single-use active are affected. Other than that, I'll check which item have strange effect

**Comment by magagnato4106** [comment]
Regarding the checking, only D12 and Everthing Jar are imho the only ones which should be mentioned just for clarification issues.
