### ISSUE TITLE
Suggestion: Have a "detailed descriptions" add-on table that the user can toggle on or off

### ISSUE THREAD

**Issue by Buurazu** [wofsauge/External-Item-Descriptions#683]
en_us_detailed was not being maintained by anybody, as the regular en_us descriptions have been getting more and more refined, but perhaps now en_us is getting too detailed for a new player, especially as many Repentance items are extremely deep in what they do.

Instead of a separate language, more detailed descriptions could be implemented with a table of description appends/replaces/findreplaces. Most descriptions wouldn't be touched, while some items with more complicated formulas or mechanics behind them can be made simpler for new players, getting the gist across rather than trying to squeeze every useful detail in.

This would also enable every language to have its own "detailed" mode if they wish.

Examples:
Cube Of Meat's levels; what damage do they do? That description has been extremely simplified. Bumbo on the other hand could stand to be simpler
Stuff like Chocolate Milk's max charge time as "tear delay x2.5"
Items like Cracked Dice can define their potential effects better?
"Luck" requirements: Only keep ones that are affected by low luck amounts (especially 10 or less; perfection) in basic descs, detailed descs can have ones that are nearly pointless
4.5 Volt: Exact damage needed formula of how it increases per floor
Berserk: Include how you can't die while it's active
Alabaster Box: being weaker if you've taken a devil deal, is that necessary info?
Some specific damage numbers might not be worthy of the simple mode, like the exact damage that a candle fire does
Explosions that ignore / don't ignore boss armor
Anima Sola spawning Esau early if used in empty room before he's spawned
Tainted Eden item pools are complicated (based on last room entered if you backtrack to an earlier spawned pedestal, or something like that)
Tainted Cain salvaging details: 4-6 items, reveal the percentages (first pickup has special rules), pennies are 1-3, hearts can reduce pickups

I'm personally not great at making simple descs so I don't know just how much to cut but I think biobak (whose idea this is) would really like to simplify things like "0.4x tears multiplier, +2 tear delay" to just "big tears down" and that might be a nice option

**Comment by Buurazu** [comment]
Thinking more about this, these shouldn't be in a separate table from the rest of the descriptions. Since this is so directly connected to the original description, I'm thinking that instead it can be part of the original description's table. Either as a 4th entry, or maybe specified as being ["detailed"] to keep it clear what the text is for.

**Comment by wofsauge** [comment]
this would make all the descriptions vastly more complicated and adds way more work to the already tedious task of translating the mod. We cant please all of the people, so i am willing to sacrifice super detailed descriptions in favor of maintainability of the whole mod. I am not a fan of the idea, so i will close this issue for now.
