### ISSUE TITLE
Bag of crafting save exit and restart

### ISSUE THREAD

**Issue by DikaMahardika** [wofsauge/External-Item-Descriptions#687]
Bag of crafting recipes somehow not valid after resetting (pressing R) or save and exitting the game.

**Comment by Buurazu** [comment]
is this with the new Learned Recipe List setting? is it that previous run recipes are staying in a new run?
I've just tested having a few learned recipes and resetting and am not able to reproduce any strange behavior, so I'm not sure what you're reporting without a more clear report and screenshot proof of something

**Comment by DikaMahardika** [comment]
i can't reproduce it too now, weird. it happened all the time yesterday. sorry. 
it's error on my side probably

yesterday I'm trying to craft diplo but i was exit the game first, when i play back in, the recipe for diplo gone. then i just restart the game and try to craft another item, it show as different item even tho it's the same as in description recipe.

**Comment by Buurazu** [comment]
If you're on the default recipe list, it's normal for it to not save it when exiting the game, since it calculates thousands of recipes we don't save them anywhere.
