### ISSUE TITLE
How to add extra effects to "horsepills" instructions?

### ISSUE THREAD

**Issue by GoldenShit233** [wofsauge/External-Item-Descriptions#694]
I tried to add a new item in "`EID.descriptions[lang].horsepills`", but it doesn't seem to work.
For gold ornaments, however, a similar modification (insert item in "`EID.descriptions[lang].goldenTrinketEffects`") would work.
Is there a problem with my coding, or is there any missing flag, or do I need to add additional modify?

Here is part of my code
`EID.descriptions[language[1]].horsepills[value.id] = {""..value.id, value["name_"..language[2]], value["horse_"..language[2]]}`

**Comment by Buurazu** [comment]
The problem is that the pill description table is not zero indexed; horsepills[1] = pill effect 0

I've added an EID:addHorsePill api function that will take care of that for you just like EID:addPill does. It'll be available after the next EID update.
