### ISSUE TITLE
Methods cannot be called properly because some languages lack a subtable with descriptions.

### ISSUE THREAD

**Issue by GoldenShit233** [wofsauge/External-Item-Descriptions#712]
In some languages, such as "zh_cn", do not has subtable in EID.descriptions, which would make some method unusable.
Here is an example:
```
EID:addBFFSCondition(id, text, false, false, "zh_cn")
```
sometimes, would lead error like "attempt to index a nil value (field 'BFFSynergies')". And for "zh_cn", it also happend on`EID:addCharacterInfo`.

It can be solved in this way:
```
if not EID.descriptions[language].BFFSSynergies then
	EID.descriptions[language].BFFSSynergies = {}
end
```
Maybe should  put a check statement in front of each of these methods?

**Comment by wofsauge** [comment]
this issue is fixed now. thanks for the report :)

will push the update to the workshop soon
