### ISSUE TITLE
Mod not visible on cracked isaac

### ISSUE THREAD

**Issue by Penchorus** [wofsauge/External-Item-Descriptions#718]
I'm playing with the Isaac Repentance dlc, but the game was downloaded for free from the internet. When using the mod config menu, I can access the mod's settings, but I cannot see the mod in the game. Do I need to change a setting (or something) to see it?

**Comment by wofsauge** [comment]
Please make sure you have the correct version of the mod installed, by following the install instructions provided here:

https://github.com/wofsauge/External-Item-Descriptions/wiki/How-to-install-the-mod#epic-games--gog--cracked

If the problem you have still occurs after installing the correct version, please send the log.txt file found here
`C:\Users\[username]\Documents\My Games\Binding of Isaac Repentance\`

**Comment by Penchorus** [comment]
> Please make sure you have the correct version of the mod installed, by following the install instructions provided here:
> 
> https://github.com/wofsauge/External-Item-Descriptions/wiki/How-to-install-the-mod#epic-games--gog--cracked
> 
> If the problem you have still occurs after installing the correct version, please send the log.txt file found here `C:\Users\[username]\Documents\My Games\Binding of Isaac Repentance\`

I'm using Isaac's 1.7.5.0000 version. I couldn't find a suitable link. Can you give me a link?
![Uploading resim_2024-09-06_105820172.png…]()

**Comment by wofsauge** [comment]
Download a newer version of the game then. 1.7.5 is a 4 year old version, and there where like 8 patches afterwards, including patches that fix bigger bugs and issues

**Comment by Penchorus** [comment]
:(
