### ISSUE TITLE
AddClosestPlayerConditional does not seem to include the tainted variant by default

### ISSUE THREAD

**Issue by Tiburones202** [wofsauge/External-Item-Descriptions#722]
Items such as Candy Heart or Empty Heart for lost do not seem to get their descriptions replaced with the tainted variant of the character.
The same is true for keeper.

Adding "True" to the "includeTainted" field in it fixes this

**Comment by Buurazu** [comment]
Ah, it wasn't defaulting it to true, thanks for the report, is fixed now
