### ISSUE TITLE
Magdalene's starting Full Health Pill not identified

### ISSUE THREAD

**Issue by torzod** [wofsauge/External-Item-Descriptions#734]
Magdalene starts with a pre-identified Full Health pill, and this also identifies all other encountered Full Health pills, though EID does not seem to realize that the pill is identified.
![image](https://github.com/user-attachments/assets/d000f49f-49bb-45b0-a9f4-59e91cd8226b)
This can be easily tested with seed E2HE 3YHD, as a full health pill will spawn in the chest in the L-shaped room on the first floor.

**Comment by torzod** [comment]
This should not apply to Lazarus's starting pill, as according to the wiki it starts out unidentified, but may apply to Eden's occasional starting pill, as the wiki does not mention whether or not it starts off identified.

**Comment by wofsauge** [comment]
On the same seed, the pill is identified for me right from the start. I tested both with and without Repentogon enabled.
Do you maybe have a mod installed, that adds extra pill effects?

![image](https://github.com/user-attachments/assets/764419d3-39b5-43c0-b359-515911be2d9f)

**Comment by torzod** [comment]
this is odd, as i do not have any other mods installed that have any pill changes. I do have "show pill effect after one use" enabled in settings though, as I wanted to better approximate how a player would identify pills, though it seems there is no good way to do so.

**Comment by wofsauge** [comment]
ok i found the issue for both problems.

For magdalene, her starting pill was not counted towards the already used pills, which made it not being identified with the "show pill effect after one use" setting active.

For the Temperance? card, we intentionally not counted those used towards the "used"-list of the setting. but you are right, the animation of the card does show the pill being used, and therefore it makes sense that they should be identified if Temperance? was used.

Thank you for the report :)
