### ISSUE TITLE
Suggestion: Add includeTainted parameter to addPlayerCondition

### ISSUE THREAD

**Issue by nazjun** [wofsauge/External-Item-Descriptions#737]
I've been picking through the API to figure out how to get my modded character/item descriptions to be as succinct as possible, and I noticed that the API function `addPlayerCondition` calls `AddPlayerConditional` without specifying a value for `includeTainted`, thereby making it always default to true within the body of `AddPlayerConditional` and removing a degree of flexibility for character descriptions.

I could always reimplement the `addPlayerCondition` method in my own mod code to let me pass an extra argument to `AddPlayerConditional`, but it's a bit of an inconvenience that the flag isn't exposed to the function modders are intended to be using. All that really needs to be done is change the definition in `eid_conditionals_funcs.lua` to:
```lua
function EID:addPlayerCondition(ID, playerID, text, replaceText, language, extraTable, includeTainted)
	language = language or "en_us"
	if replaceText then text = {text, replaceText} end
	local modifierText = newModdedCondition(text, language)
	EID:AddPlayerConditional(ID, playerID, modifierText, extraTable, includeTainted)
end
```
...unless there's some caveat to allowing this that I'm not aware of?
Anyway, sorry about the nitpickiness. You've done several gods' work by putting all this together to begin with.

**Comment by Buurazu** [comment]
Sure, done. I think I was thinking "modded characters won't be detected as tainted" so left it off, but I suppose modded items can have specific effects on specific vanilla chars too

**Comment by nazjun** [comment]
Ah, I see what you mean. Digging deeper, the tainted check is a manual list in the mod code that only checks vanilla characters, and not programmatic as I'd expected. I recall `EntityConfig` is a REPENTOGON invention anyways, so it wouldn't exactly be easy to do that. (I only started this a month ago, so RGON is hard carrying me, lmao.)

Thanks though! It's good to have that extra control, I feel.
