### ISSUE TITLE
Diplopia hints not going away when consumed by void

### ISSUE THREAD

**Issue by torzod** [wofsauge/External-Item-Descriptions#740]
when diplopia is consumed by the void, diplopia hints ("cannot be duplicated") are shown, however unlike normal diplopia, these hints do not go away when the void's diplopia is consumed.
![image](https://github.com/user-attachments/assets/80a0af59-06aa-424b-b677-8f70276158f7)
note the voided items indicators. i had previously voided diplopia in this run, but it is no longer present in the void, as i have used it.

**Comment by wofsauge** [comment]
This issue should be fixed for all single use active items now as well :)

Thank you for the rport
