### ISSUE TITLE
How to fix External item descriptions not working? [repentance cracked. don't remember version]

### ISSUE THREAD

**Issue by simonplays21** [wofsauge/External-Item-Descriptions#741]
When I load into repentance and go into mods it shows up as enabled but when I enter the game it doesn't show my items or their descriptions/not loading pressing  F2 doesn't fix it so how to I fix it?

**Comment by wofsauge** [comment]
Please make sure to follow the install instructions for cracked versions of the game: https://github.com/wofsauge/External-Item-Descriptions/wiki/How-to-install-the-mod#epic-games--gog--cracked
