### ISSUE TITLE
Dose EID supports Repentance+?

### ISSUE THREAD

**Issue by breaking153** [wofsauge/External-Item-Descriptions#748]
multiplayer EID tests Needed !!

**Comment by f1amy** [comment]
afaik no mods support online, as they are disabled during multiplayer

we would need a hack like this to make it work
https://github.com/wofsauge/External-Item-Descriptions/wiki/Use-EID-in-Online-Coop-(Beta)

**Comment by wofsauge** [comment]
> afaik no mods support online, as they are disabled during multiplayer
> 
> we would need a hack like this to make it work https://github.com/wofsauge/External-Item-Descriptions/wiki/Use-EID-in-Online-Coop-(Beta)

The link you send refers to an old tutorial which should not be done anymore. I deleted the page for good now.

To answer the question of the issue:

Mods do work in online coop, but they need to be manually put in a special folder. For windows its:
../Documents/My Games/Repentance+/Mods

We will update our install instructions once we are sure the mod works in the new dlc. This will also entail a new version of the mod that works better in online coop and contains all the balance changes made to the items

Please be patient

**Comment by f1amy** [comment]
@wofsauge 
> Mods do work in online coop, but they need to be manually put in a special folder.

From the announcement:
> **Q: Can I play with mods online?**
A: No, all mods must be disabled and the game restarted in order to play online.

https://store.steampowered.com/news/app/250900/view/7119722540407193807

Sorry, I'm confused. Can mods really work when playing online?

**Comment by wofsauge** [comment]
Litterly the question below of the article tells you that mods do work, if you put them in the folder mentioned
> Q: Where are my mods?
A: Repentance+ has its own mods folder located here: C:\Users\YOURUSERNAME\Documents\My Games\Binding of Isaac Repentance+\mods however, it is empty. Mod creators will need to update their mods for compatibility. If you copy Repentance or AB+ mods into this folder, you DO SO AT YOUR OWN RISK as things are likely to break.

**Comment by f1amy** [comment]
> Litterly the question below of the article tells you that mods do work, if you put them in the folder mentioned
> 
> > Q: Where are my mods?
> > A: Repentance+ has its own mods folder located here: C:\Users\YOURUSERNAME\Documents\My Games\Binding of Isaac Repentance+\mods however, it is empty. Mod creators will need to update their mods for compatibility. If you copy Repentance or AB+ mods into this folder, you DO SO AT YOUR OWN RISK as things are likely to break.

I believe this means that mods will work in single player if they're updated, not online.

**Comment by f1amy** [comment]
So I figured we'd need some sort of a hack to bypass disable mods requirement as previously with beta

**Comment by wofsauge** [comment]
hmm yeah. After further testing mods do indeed not work in online mode. i misinterpreted the second info then. Sorry

i guess the same method as in the alpha can be applied, but i will need to dedicate some more time to find a more elegant solution, if possible. i dont want people to follow outdated tutorials and install outdated versions of a mod. that can cause to many unpredictable problems.

**Comment by wofsauge** [comment]
The most recent update to the game reenabled steam workshop support. The mod will now install and update itself automatically. Online mod support is still not possible, and is not planed by the game devs as far as we know.

Therefore, i will close this issue for now.
