### ISSUE TITLE
A strange question

### ISSUE THREAD

**Issue by scarfjoker** [wofsauge/External-Item-Descriptions#772]
Why is my switch using the joystick button? When I use the joystick, the button cannot be used
![Screenshot 2024-11-28 235321](https://github.com/user-attachments/assets/0faba3aa-0228-421c-aecb-f3396f6b1a3e)

**Comment by wofsauge** [comment]
the thing on the left is not a joystick icon, but a "select" or "options" button icon, commonly found on the center left of a controller:
![image](https://github.com/user-attachments/assets/83d92eb2-771b-4ea2-a51f-1444cc6b1aeb)

**Comment by scarfjoker** [comment]
> 左边的东西不是摇杆图标，而是 “Select” 或 “Options” 按钮图标，通常位于控制器的左中： ![image](https://private-user-images.githubusercontent.com/245725/390853512-83d92eb2-771b-4ea2-a51f-1444cc6b1aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzA2MDUsIm5iZiI6MTczMjg3MDMwNSwicGF0aCI6Ii8yNDU3MjUvMzkwODUzNTEyLTgzZDkyZWIyLTc3MWItNGVhMi1hNTFmLTE0NDRjYzZiMWFlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwODUxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODdiNjNlMjY0MjM2NDE4NjM1MzAxNWZiYjQzMTQ5OGY4NjYzYzZkNTE2Zjc3MjAyYzBjZDMzODYxM2ZiMDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VIthyw4WCT4z-kjJ2hHSg-MsInV7bIdm8Ni8uKGlTek)
I am a keyboard player. How can I switch it to keyboard mode

**Comment by scarfjoker** [comment]
> 左边的东西不是摇杆图标，而是 “Select” 或 “Options” 按钮图标，通常位于控制器的左中： ![image](https://private-user-images.githubusercontent.com/245725/390853512-83d92eb2-771b-4ea2-a51f-1444cc6b1aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzA2MDUsIm5iZiI6MTczMjg3MDMwNSwicGF0aCI6Ii8yNDU3MjUvMzkwODUzNTEyLTgzZDkyZWIyLTc3MWItNGVhMi1hNTFmLTE0NDRjYzZiMWFlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwODUxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODdiNjNlMjY0MjM2NDE4NjM1MzAxNWZiYjQzMTQ5OGY4NjYzYzZkNTE2Zjc3MjAyYzBjZDMzODYxM2ZiMDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VIthyw4WCT4z-kjJ2hHSg-MsInV7bIdm8Ni8uKGlTek)

How can I switch it to keyboard mode

**Comment by wofsauge** [comment]
> How can I switch it to keyboard mode

Just play the game with a keyboard, instead of a controller
