### ISSUE TITLE
Vade Retro causing errors with Repentogon

### ISSUE THREAD

**Issue by callous-crow** [wofsauge/External-Item-Descriptions#778]
This only happened while I was playing Tainted Keeper in Greedier Mode. An angel room spawned with Vade Retro, and approaching it caused some error messages, and the description for Vade Retro didn't appear on-screen.

"MC_HUD_RENDER" from "External Item Descriptions" failed: ...xternal item descriptions_836319872/features/eid_api.lua:549: attempt to concatenate a nil value (local 'adjustedID')
Stack Traceback:
  ...xternal item descriptions_836319872/features/eid_api.lua:549: in function 'getDescriptionData'
  ...xternal item descriptions_836319872/features/eid_api.lua:629: in function 'getObjectName'
  ...l item descriptions_836319872/features/eid_modifiers.lua:100: in function at line 79
  ...xternal item descriptions_836319872/features/eid_api.lua:471: in function 'applyDescriptionModifier'
  ...xternal item descriptions_836319872/features/eid_api.lua:440: in function at line 418
  ...birth/mods/external item descriptions_836319872/main.lua:1528: in function at line 1248

Strangely. starting a new game as Isaac on hard and spawning the item in did not reproduce the error. Spawning it in as Tainted Keeper in Ultra Greedier also didn't reproduce the error. I sincerely don't understand how or why this happened in the first place. I'll update with more details if I'm able to find any.

**Comment by Buurazu** [comment]
What an obscure bug to catch; this only happens as Tainted Keeper on option pedestals while holding Void and having the cheaty Void stat-ups option on. Being both a shop item AND an option item glitched the possible Void result out. There will be a fix for it next update
