### ISSUE TITLE
Souls and similar items description

### ISSUE THREAD

**Issue by ivanovishado** [wofsauge/External-Item-Descriptions#78]
Hi, I think that the description for souls could be shown when they're available to be bought since they all have different forms.

Is this possible with the current API?

**Comment by wofsauge** [comment]
what do you mean? soulstones do already have a distinct description:
![image](https://user-images.githubusercontent.com/245725/118379747-0dde3b80-b5dd-11eb-8f99-fffdf0d594d6.png)

**Comment by ivanovishado** [comment]
I was referring to when you encounter a soul in places you can buy items, like the Shop for example. In these places, if you haven't bought the soul, it doesn't display the information about it.

Sorry I don't have a screenshot at hand, this happened to me yesterday when I was playing and forgot to take it.

**Comment by ivanovishado** [comment]
@wofsauge, here's an example situation about what I was mentioning:

![imagen](https://user-images.githubusercontent.com/17692634/119944815-5b9e6080-bf5a-11eb-9eec-3f56eed94270.png)

Since souls have unique appearances, it wouldn't be considered cheaty to have the description for them in these kinds of situations.

Another example would be when a soul is available in the shop, but you need to buy it before you can read its description.

**Comment by wofsauge** [comment]
Ive added an option for that now. Sorry that it took so long
