### ISSUE TITLE
EID don't work

### ISSUE THREAD

**Issue by alekaima** [wofsauge/External-Item-Descriptions#789]
Hello, after I downloaded the latest update, the EID mod stopped working on my Isaac (cracked, but I don't remember where I downloaded it) 1.7.9b.

I pressed F2 countless times and it didn't work and it's just this mod that isn't working

**Comment by wofsauge** [comment]
Please make sure to follow the installation instructions correctly: https://github.com/wofsauge/External-Item-Descriptions/wiki/How-to-install-the-mod#epic-games--gog--cracked

If it still doesn't work, please send us the log.txt file described in the installation instructions

**Comment by alekaima** [comment]
It worked, thanks.
