### ISSUE TITLE
Alt path hidden item still visible with Devil's crown

### ISSUE THREAD

**Issue by aki-art** [wofsauge/External-Item-Descriptions#82]
While holding Devil's crown, on alt paths take the visible item, then walk out and back in; the mod now reveals the second ? item.
Does not seem to work if the visible item was an active item.
![20210517020156_1](https://user-images.githubusercontent.com/31190904/118418083-418d9400-b6b7-11eb-854e-489515017e3d.jpg)

(The trinket is swallowed on the screenshot, but it works like this regardless if swallowed or not)

**Comment by wofsauge** [comment]
This bug is fixed now. If it still appears, please reopen the issue
