### ISSUE TITLE
EID info to show after picking up an item during Curse of the Blind?

### ISSUE THREAD

**Issue by MikesJam** [wofsauge/External-Item-Descriptions#83]
To clarify, is there a way to be able to see an item's EID entry _after_ you've picked it up? With curse of the blind, even after picking up an unknown item, there's no clarification for said item. I understand that the mod has an option to ignore curse of the blind, but I feel like that spoils the intended experience. It would be really convenient to be able to see EID's info for what you just obtained, since you are able to see what the unknown item is once you've picked it up.

Thank you for your work on this invaluable mod!

**Comment by wofsauge** [comment]
This bug should be fixed now. Thanks for the report
