### ISSUE TITLE
Local render text under item mode

### ISSUE THREAD

**Issue by kochetov2000** [wofsauge/External-Item-Descriptions#84]
It would be nice to implement a local rendering mode of the text under the item instead of the fixed location of the text in the upper left corner on a smaller scale to save screen space as implemented in yetanother's External Item Descriptions modification https://steamcommunity.com/sharedfiles/filedetails/?id=1144059613

**Comment by kochetov2000** [comment]
After a long time I managed to implement the above, but I am also doing something else additionally

**Comment by wofsauge** [comment]
> After a long time I managed to implement the above, but I am also doing something else additionally

Awesome 👌 
Can't wait for the PR then ;)

**Comment by wofsauge** [comment]
Pr added this feature now :)
