### ISSUE TITLE
Inaccessible card descriptions still shown for one frame

### ISSUE THREAD

**Issue by rytisbitcoin** [wofsauge/External-Item-Descriptions#94]
When entering the room, the description of the card is still shown for one (?) frame, then it changes to "?". Exiting and reentering the room shows the description for one (?) frame again. If this happens because it takes time to calculate whether the card is inaccessible, it could be solved by changing the logic from: "show the card description unless it's inaccessible" to: "hide the card description unless it's not inaccessible".

**Comment by rytisbitcoin** [comment]
Did not test with pills.

**Comment by wofsauge** [comment]
This bug is fixed now. thanks for the report
