### ISSUE TITLE
Russian language support in mod Deliverance

### ISSUE THREAD

**Issue by SashaKillmagik** [wofsauge/External-Item-Descriptions#97]
It would be nice if they returned the Russian language to the mod Deliverance. Everything has already been translated, it remains only to add it to the mod and people will be happy.

Link to mod Deliverance
https://steamcommunity.com/sharedfiles/filedetails/?id=1762369129

in the very fashion there was a link to the Russian description
https://docs.google.com/document/d/e/2PACX-1vQHE9UWX5IS6o7y7nu7Qo9SUiOt761zK9j3_f283lFydhhTBcgVEJjHJUSgbPRz1WdKORXdcfhGMFpI/pub?embedded=true

**Comment by wofsauge** [comment]
EID does only provide an API for other mods to add descriptions into. it does not store them itself. Therefore your need to message the Deliverance mod team to add support for their items.

Closed this issue since it has nothing todo with EID.
