### ISSUE TITLE
Descriptions for custom EntityEffects

### ISSUE THREAD

**Issue by ShenanigansBunul** [wofsauge/External-Item-Descriptions#98]
I am writing a mod that has custom EntityEffects that I want to include EID support for, but I am recently having an issue where the descriptions no longer show up. The way I do it is by using the "EID_Description" key in the entity data.

After investigating more I found out that EntityEffects are currently simply ignored by Isaac.FindInRadius, even if you partition for effects. This means that this commit (https://github.com/wofsauge/External-Item-Descriptions/commit/a86992ae7d722e59e63e104f3d5b2654b6adc707) that changed the way entities are obtained on render has made it impossible for custom EntityEffects to have EID descriptions, as they're just not in the list of entities anymore.

Isaac.GetRoomEntities has the custom EntityEffects in the returned list, but it's also currently apparently less efficient than FindInRadius.

If returning to using GetRoomEntities is not an option, would it be possible to include a feature in the API where you can add entities to a list that would always be appended to the entities list obtained using FindInRadius? This way, to include custom EntityEffect descriptions for their mod, one would have to add the entities to that list while also setting their description.

**Comment by wofsauge** [comment]
Hey. Ive Added a second query for effect entities now. The workshop will update with it after i did some other bugfixes.

I hope this will fix your issues :)

**Comment by ShenanigansBunul** [comment]
Thanks a lot for the fix, I cloned the latest version of the mod and the custom EntityEffects show their descriptions again.
